In [1]:
import pandas as pd
import numpy as np
import json
import re

In [2]:
with open("2018-02-14_focus_discussion/2018-02-14_focus_group.json", 'r', encoding='UTF-8') as focus_group:
    focus = json.load(focus_group)

In [3]:
with open("krx_code.json", 'r', encoding='UTF-8') as krx:
    krx_code = json.load(krx)

In [4]:
with open("2018-02-14_opening_increase.json", 'r', encoding='UTF-8') as oi:
    INCREASE = json.load(oi)

In [5]:
with open("2018-02-14_price_and_everything.json", 'r', encoding='UTF-8') as oi:
    price = json.load(oi)

In [54]:
time = []

prefix = "2018-02-14_focus_discussion/discussion_2018-02-14"
for hour in range(9,16):
    for minute in range(0, 6):
        time.append(prefix + " " + (("0" + str(hour)) if hour <= 9 else str(hour))+ \
                    ":" + str(minute) + "0.json")

In [55]:
del time[41]
del time[40]

In [56]:
discussion_list = []
for x in time[1: ]:
    with open(x, 'r', encoding='UTF-8') as f:
        discussion = json.load(f)        
        discuss_df = pd.DataFrame(discussion, columns = ["post_num", \
                            "unique_id", "click", "like", "dislike", 
                            "name", "time"])
        reset_col = ["name", "time", "post_num", "unique_id", "click", \
                     "like", "dislike"]
        discuss_df = discuss_df[reset_col]
        discussion_list.append(discuss_df)

In [57]:
def list_to_df(df_list, column_names, key_list):
    total = pd.DataFrame(columns=column_names)
    for ind, df in enumerate(df_list):
        if ((ind + 1) % 3  == 0) and (ind != 2):
            df_total = df.merge(df_list[ind - 5], on = \
                                key_list).merge(df_list[ind - 4], \
                                on = key_list).merge(df_list[ind - 3], on = key_list)
            df_total.columns = column_names
            total = pd.concat([total, df_total], axis = 0)
            total = total[total["name"].isin(INCREASE)]
    return total

In [58]:
COLUMN_NAMES=["name", "time", "post_num", "unique_id", "click", \
              "like", "dislike", "time_1", "post_num_1", "unique_id_1", "click_1", \
              "like_1", "dislike_1", "time_2", "post_num_2", "unique_id_2", "click_2", \
              "like_2", "dislike_2", "time_3", "post_num_3", "unique_id_3", "click_3", \
              "like_3", "dislike_3"]
discuss_df = list_to_df(discussion_list, COLUMN_NAMES, 
                        ['name']).reset_index().drop(["index"], axis = 1)

In [59]:
price_df = pd.DataFrame(price, columns = ["index", "code", "name", "time", "price", \
                                         "price_dif", "sell", "buy", "volume", "variation"])
price_df = price_df[["code", "name", "time", "price", \
                    "price_dif", "sell", "buy", "volume", "variation"]][1:]
price_df = price_df[price_df["time"] != "2018-02-14 09:00"]

In [60]:
time_list = price_df['time'].unique().tolist()
price_df_list = []
for time in time_list:
    df = price_df[price_df["time"] == time]
    df = df[["code", "name", "time", "price", \
            "price_dif", "sell", "buy", "volume", "variation"]]
    price_df_list.append(df)

In [61]:
COLUMN_PRICE=["code", "name", "time", "price", "price_dif", "sell", 
              "buy", "volume", "variation", "time_1", "price_1", 
              "price_dif_1", "sell_1", "buy_1", "volume_1", "variation_1",
              "time_2", "price_2", "price_dif_2", "sell_2", "buy_2", 
              "volume_2", "variation_2", "time_3", "price_3", 
              "price_dif_3", "sell_3", "buy_3", "volume_3", "variation_3"]
price_df = list_to_df(price_df_list, COLUMN_PRICE, \
                      ['code', 'name']).reset_index().drop(["index"], axis = 1)

In [62]:
price_df.set_index("name")
discuss_df.set_index("name")

,time,post_num,unique_id,click,like,dislike,time_1,post_num_1,unique_id_1,click_1,...,unique_id_2,click_2,like_2,dislike_2,time_3,post_num_3,unique_id_3,click_3,like_3,dislike_3
name,,,,,,,,,,,,,,,,,,,,,
호텔신라,2018-02-14 10:00,7,5,937,13,6,2018-02-14 09:10,4,3,260,...,4,459,7,4,2018-02-14 09:30,5,4,571,7,4
대한광통신,2018-02-14 10:00,6,5,627,6,4,2018-02-14 09:10,0,0,0,...,0,0,0,0,2018-02-14 09:30,3,3,142,1,3
포스코 ICT,2018-02-14 10:00,3,3,1123,2,9,2018-02-14 09:10,2,2,542,...,2,656,1,4,2018-02-14 09:30,3,3,781,1,5
한화케미칼,2018-02-14 10:00,9,8,1094,10,15,2018-02-14 09:10,2,2,405,...,3,529,2,7,2018-02-14 09:30,6,6,706,3,8
지엘팜텍,2018-02-14 10:00,4,4,1416,9,14,2018-02-14 09:10,3,3,472,...,4,751,4,10,2018-02-14 09:30,4,4,970,8,12
코웰패션,2018-02-14 10:00,2,2,267,1,0,2018-02-14 09:10,1,1,67,...,1,91,1,0,2018-02-14 09:30,1,1,121,1,0
대한항공,2018-02-14 10:00,5,3,469,1,4,2018-02-14 09:10,0,0,0,...,1,19,0,0,2018-02-14 09:30,2,2,70,0,0
대한뉴팜,2018-02-14 10:00,1,1,63,0,3,2018-02-14 09:10,1,1,5,...,1,36,3,3,2018-02-14 09:30,1,1,64,3,3
레드캡투어,2018-02-14 10:00,0,0,0,0,0,2018-02-14 09:10,0,0,0,...,0,0,0,0,2018-02-14 09:30,0,0,0,0,0
이마트,2018-02-14 10:00,1,1,53,5,0,2018-02-14 09:10,0,0,0,...,1,6,2,0,2018-02-14 09:30,1,1,23,2,0
녹십자,2018-02-14 10:00,2,2,270,3,0,2018-02-14 09:10,1,1,143,...,1,157,3,0,2018-02-14 09:30,1,1,175,3,0
GS,2018-02-14 10:00,1,1,185,3,1,2018-02-14 09:10,1,1,138,...,1,148,3,0,2018-02-14 09:30,1,1,156,3,0
CJ헬로,2018-02-14 10:00,4,2,530,1,1,2018-02-14 09:10,1,1,61,...,1,97,1,1,2018-02-14 09:30,2,2,129,1,1
모토닉,2018-02-14 10:00,0,0,0,0,0,2018-02-14 09:10,0,0,0,...,0,0,0,0,2018-02-14 09:30,0,0,0,0,0
AJ렌터카,2018-02-14 10:00,3,3,246,8,1,2018-02-14 09:10,2,2,113,...,2,146,6,1,2018-02-14 09:30,2,2,163,6,1
한국전자홀딩스,2018-02-14 10:00,1,1,10,0,0,2018-02-14 09:10,0,0,0,...,0,0,0,0,2018-02-14 09:30,0,0,0,0,0
일진머티리얼즈,2018-02-14 10:00,20,11,3921,51,46,2018-02-14 09:10,12,7,1980,...,9,2431,33,36,2018-02-14 09:30,16,9,2871,36,38
코위버,2018-02-14 10:00,1,1,7,0,0,2018-02-14 09:10,0,0,0,...,0,0,0,0,2018-02-14 09:30,0,0,0,0,0
앱클론,2018-02-14 10:00,3,2,221,2,0,2018-02-14 09:10,0,0,0,...,0,0,0,0,2018-02-14 09:30,1,1,19,0,0
디에이치피코리아,2018-02-14 10:00,2,2,416,1,0,2018-02-14 09:10,3,3,200,...,3,267,0,0,2018-02-14 09:30,3,3,337,1,0
지스마트글로벌,2018-02-14 10:00,17,14,3245,29,20,2018-02-14 09:10,3,3,1146,...,7,1750,15,11,2018-02-14 09:30,10,8,2295,21,18
씨케이에이치,2018-02-14 10:00,8,5,622,12,3,2018-02-14 09:10,2,2,278,...,3,305,5,2,2018-02-14 09:30,4,4,357,6,2
삼우엠스,2018-02-14 10:00,1,1,64,1,0,2018-02-14 09:10,1,1,36,...,1,41,1,0,2018-02-14 09:30,1,1,49,1,0
인트론바이오,2018-02-14 10:00,2,2,350,1,2,2018-02-14 09:10,2,2,129,...,2,203,0,2,2018-02-14 09:30,2,2,263,1,2
휴온스,2018-02-14 10:00,0,0,0,0,0,2018-02-14 09:10,0,0,0,...,0,0,0,0,2018-02-14 09:30,0,0,0,0,0
알서포트,2018-02-14 10:00,3,2,78,0,0,2018-02-14 09:10,0,0,0,...,0,0,0,0,2018-02-14 09:30,0,0,0,0,0
에스에너지,2018-02-14 10:00,2,2,61,0,0,2018-02-14 09:10,0,0,0,...,1,17,0,0,2018-02-14 09:30,1,1,31,0,0
키움증권,2018-02-14 10:00,0,0,0,0,0,2018-02-14 09:10,0,0,0,...,0,0,0,0,2018-02-14 09:30,0,0,0,0,0
녹십자셀,2018-02-14 10:00,7,5,567,12,4,2018-02-14 09:10,1,1,20,...,2,56,3,0,2018-02-14 09:30,4,4,168,5,2
성광벤드,2018-02-14 10:00,0,0,0,0,0,2018-02-14 09:10,0,0,0,...,0,0,0,0,2018-02-14 09:30,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
에이프로젠제약,2018-02-14 15:30,78,30,19928,215,97,2018-02-14 14:40,75,30,17801,...,30,18337,207,92,2018-02-14 15:00,79,31,18776,208,92
지니언스,2018-02-14 15:30,6,4,411,1,1,2018-02-14 14:40,5,4,402,...,4,409,1,1,2018-02-14 15:00,5,4,422,1,1
이녹스첨단소재,2018-02-14 15:30,6,6,2159,6,2,2018-02-14 14:40,3,3,1061,...,3,1234,5,1,2018-02-14 15:00,4,4,1459,5,1
KG ETS,2018-02-14 15:30,0,0,0,0,0,2018-02-14 14:40,0,0,0,...,0,0,0,0,2018-02-14 15:00,0,0,0,0,0
삼기오토모티브,2018-02-14 15:30,2,2,170,2,1,2018-02-14 14:40,2,2,113,...,2,122,2,1,2018-02-14 15:00,2,2,148,2,1
현대로템,2018-02-14 15:30,5,5,1195,19,6,2018-02-14 14:40,5,5,1053,...,5,1076,19,6,2018-02-14 15:00,5,5,1110,19,6
서진오토모티브,2018-02-14 15:30,3,3,452,4,5,2018-02-14 14:40,3,3,406,...,3,412,4,5,2018-02-14 15:00,3,3,419,4,5
삼본정밀전자,2018-02-14 15:30,6,4,293,10,0,2018-02-14 14:40,6,4,251,...,4,253,9,0,2018-02-14 15:00,6,4,255,10,0
테라젠이텍스,2018-02-14 15:30,23,18,6950,41,24,2018-02-14 14:40,25,19,6473,...,18,6445,39,24,2018-02-14 15:00,24,18,6574,39,24
이오테크닉스,2018-02-14 15:30,6,6,815,4,7,2018-02-14 14:40,5,5,664,...,5,681,4,7,2018-02-14 15:00,6,6,710,4,7
이화전기,2018-02-14 15:30,54,40,16308,126,99,2018-02-14 14:40,50,37,14807,...,37,15080,124,93,2018-02-14 15:00,51,37,15317,124,95
한온시스템,2018-02-14 15:30,3,3,1834,4,8,2018-02-14 14:40,3,3,1716,...,3,1745,4,6,2018-02-14 15:00,3,3,1768,4,8
신송홀딩스,2018-02-14 15:30,1,1,34,3,0,2018-02-14 14:40,1,1,16,...,1,20,2,0,2018-02-14 15:00,1,1,27,2,0
락앤락,2018-02-14 15:30,8,7,2779,21,8,2018-02-14 14:40,10,8,2654,...,8,2881,23,10,2018-02-14 15:00,10,8,2984,24,10
메디포스트,2018-02-14 15:30,28,17,9494,79,31,2018-02-14 14:40,28,17,8574,...,16,8726,69,24,2018-02-14 15:00,26,16,8924,71,25
SK디스커버리,2018-02-14 15:30,1,1,200,7,1,2018-02-14 14:40,1,1,123,...,1,139,7,0,2018-02-14 15:00,1,1,152,7,0
테라세미콘,2018-02-14 15:30,23,15,6602,52,41,2018-02-14 14:40,22,15,5250,...,15,5665,50,31,2018-02-14 15:00,22,15,5876,51,31
지엠비코리아,2018-02-14 15:30,7,6,944,9,3,2018-02-14 14:40,9,7,877,...,7,917,8,3,2018-02-14 15:00,7,6,907,8,3
대원산업,2018-02-14 15:30,1,1,130,2,0,2018-02-14 14:40,1,1,117,...,1,122,2,0,2018-02-14 15:00,1,1,124,2,0
바디텍메드,2018-02-14 15:30,3,3,1275,8,7,2018-02-14 14:40,3,3,1133,...,3,1150,8,7,2018-02-14 15:00,3,3,1172,8,7
한국금융지주,2018-02-14 15:30,2,2,584,5,0,2018-02-14 14:40,2,2,539,...,2,546,5,0,2018-02-14 15:00,2,2,556,5,0
현대비앤지스틸,2018-02-14 15:30,2,2,267,2,1,2018-02-14 14:40,2,2,206,...,2,213,2,1,2018-02-14 15:00,2,2,220,2,1
동양,2018-02-14 15:30,6,6,1920,47,9,2018-02-14 14:40,6,6,1687,...,6,1739,47,9,2018-02-14 15:00,6,6,1766,47,9
네오위즈,2018-02-14 15:30,22,13,4950,63,25,2018-02-14 14:40,21,12,4492,...,12,4588,58,25,2018-02-14 15:00,21,12,4661,59,25
세아베스틸,2018-02-14 15:30,4,3,250,4,3,2018-02-14 14:40,4,3,140,...,3,177,4,3,2018-02-14 15:00,4,3,194,4,3
세운메디칼,2018-02-14 15:30,4,4,562,3,4,2018-02-14 14:40,3,3,436,...,3,461,3,4,2018-02-14 15:00,3,3,477,3,4
디에스티로봇,2018-02-14 15:30,24,19,5395,20,15,2018-02-14 14:40,24,17,4787,...,18,4950,17,11,2018-02-14 15:00,23,18,4997,20,14
엘엠에스,2018-02-14 15:30,2,2,301,5,1,2018-02-14 14:40,2,2,245,...,2,251,5,1,2018-02-14 15:00,3,3,258,5,1
옵트론텍,2018-02-14 15:30,4,4,1278,4,6,2018-02-14 14:40,4,4,1148,...,4,1185,4,6,2018-02-14 15:00,4,4,1203,4,6
한컴MDS,2018-02-14 15:30,3,3,679,9,7,2018-02-14 14:40,3,3,437,...,3,485,8,4,2018-02-14 15:00,3,3,538,9,4

In [64]:
total = pd.merge(price_df, discuss_df, on = ['name', 'time', 'time_1', 'time_2', 'time_3'])
total = total[['name', 'code', 'time', 'price', 'time_1', "price_1", 
              "price_dif_1", "sell_1", "buy_1", "volume_1", "variation_1", 'post_num_1',
              'unique_id_1', 'click_1', 'like_1', 'dislike_1', 
              'time_2', 'price_2', "price_dif_2", "sell_2", "buy_2", 
              "volume_2", "variation_2", 'post_num_2', 'unique_id_2', 'click_2', 'like_2',
              'dislike_2', 'time_3', 'price_3', "price_dif_3", "sell_3", "buy_3", 
              "volume_3", "variation_3", 'post_num_3', 'unique_id_3', 'click_3', 'like_3', 'dislike_3']]

In [51]:
total.columns

Index(['name', 'code', 'time', 'price', 'time_1', 'price_1', 'price_dif_1',
       'sell_1', 'buy_1', 'volume_1', 'variation_1', 'unique_id_1', 'click_1',
       'like_1', 'dislike_1', 'time_2', 'price_2', 'price_2', 'price_dif_2',
       'sell_2', 'buy_2', 'volume_2', 'variation_2', 'post_num_2',
       'unique_id_2', 'click_2', 'like_2', 'dislike_2', 'time_3', 'price_3',
       'price_dif_3', 'sell_3', 'buy_3', 'volume_3', 'variation_3',
       'unique_id_3', 'click_3', 'like_3', 'dislike_3', 'mkt_cap', 'kospi',
       'kosdaq', 'trash'],
      dtype='object')

In [65]:
import numpy as np
import re

with open("company_size.json", 'r', encoding='UTF-8') as f:
    company_size = json.load(f)

company_df = pd.DataFrame({"company_name": np.zeros(0), \
                           "code": np.zeros(0), "market": np.zeros(0), 
                          "company_size": np.zeros(0)})

company_df = pd.DataFrame(company_size, columns = ["name", "code", "market", "size"])

KOSPI = []
KOSDAQ = []
TRASH = []
MKT_CAP = {}

for idx, row in company_df.iterrows():
    if re.sub('[0-9 ,위]', '', row["market"]) == "코스피":
        KOSPI.append(row["code"])
    elif re.sub('[0-9 ,위]', '', row["market"]) == "코스닥":
        KOSDAQ.append(row["code"])
    else:
        TRASH.append(row["code"])
    
    MKT_CAP[row["code"]] = int(re.sub('[조억원,]', '', row["size"]))

In [66]:
total["mkt_cap"] = np.nan
total["kospi"] = np.nan
total["kosdaq"] = np.nan
total["trash"] = np.nan

In [67]:
total

,name,code,time,price,time_1,price_1,price_dif_1,sell_1,buy_1,volume_1,...,variation_3,post_num_3,unique_id_3,click_3,like_3,dislike_3,mkt_cap,kospi,kosdaq,trash
0,호텔신라,008770,2018-02-14 10:00,"83,400",2018-02-14 09:10,"84,700","1,800","84,800","84,700","29,336",...,"2,036",5,4,571,7,4,NaN,NaN,NaN,NaN
1,대한광통신,010170,2018-02-14 10:00,"7,050",2018-02-14 09:10,"7,060",90,"7,060","7,050","101,713",...,"3,467",3,3,142,1,3,NaN,NaN,NaN,NaN
2,포스코 ICT,022100,2018-02-14 10:00,"8,320",2018-02-14 09:10,"8,310",0,"8,330","8,310","44,311",...,"1,712",3,3,781,1,5,NaN,NaN,NaN,NaN
3,한화케미칼,009830,2018-02-14 10:00,"32,350",2018-02-14 09:10,"32,700",550,"32,700","32,650","32,647",...,"3,102",6,6,706,3,8,NaN,NaN,NaN,NaN
4,지엘팜텍,204840,2018-02-14 10:00,"4,760",2018-02-14 09:10,"4,680",50,"4,700","4,680","114,565",...,"2,844",4,4,970,8,12,NaN,NaN,NaN,NaN
5,코웰패션,033290,2018-02-14 10:00,"5,350",2018-02-14 09:10,"5,270",90,"5,280","5,270","22,780",...,"1,530",1,1,121,1,0,NaN,NaN,NaN,NaN
6,대한항공,003490,2018-02-14 10:00,"35,900",2018-02-14 09:10,"35,700",300,"35,750","35,700","7,560",...,"1,028",2,2,70,0,0,NaN,NaN,NaN,NaN
7,대한뉴팜,054670,2018-02-14 10:00,"13,750",2018-02-14 09:10,"13,800",0,"13,800","13,750","2,556",...,365,1,1,64,3,3,NaN,NaN,NaN,NaN
8,레드캡투어,038390,2018-02-14 10:00,"15,350",2018-02-14 09:10,"15,350",100,"15,350","15,200",7,...,1,0,0,0,0,0,NaN,NaN,NaN,NaN
9,이마트,139480,2018-02-14 10:00,"290,000",2018-02-14 09:10,"283,500","5,000","284,000","283,500","8,469",...,75,1,1,23,2,0,NaN,NaN,NaN,NaN
10,녹십자,006280,2018-02-14 10:00,"204,500",2018-02-14 09:10,"201,000","1,500","201,000","200,000",910,...,581,1,1,175,3,0,NaN,NaN,NaN,NaN
11,GS,078930,2018-02-14 10:00,"63,000",2018-02-14 09:10,"62,600",100,"62,700","62,600","2,353",...,219,1,1,156,3,0,NaN,NaN,NaN,NaN
12,CJ헬로,037560,2018-02-14 10:00,"8,980",2018-02-14 09:10,"8,650",230,"8,650","8,640","22,839",...,"2,134",2,2,129,1,1,NaN,NaN,NaN,NaN
13,모토닉,009680,2018-02-14 10:00,"10,150",2018-02-14 09:10,"10,300",50,"10,300","10,200","1,289",...,50,0,0,0,0,0,NaN,NaN,NaN,NaN
14,AJ렌터카,068400,2018-02-14 10:00,"10,500",2018-02-14 09:10,"10,400",0,"10,550","10,400","22,181",...,3,2,2,163,6,1,NaN,NaN,NaN,NaN
15,한국전자홀딩스,006200,2018-02-14 10:00,799,2018-02-14 09:10,795,-3,795,793,203,...,"1,979",0,0,0,0,0,NaN,NaN,NaN,NaN
16,일진머티리얼즈,020150,2018-02-14 10:00,"32,300",2018-02-14 09:10,"32,300",350,"32,250","32,200","11,043",...,724,16,9,2871,36,38,NaN,NaN,NaN,NaN
17,코위버,056360,2018-02-14 10:00,"7,790",2018-02-14 09:10,"7,870",120,"7,890","7,870","9,193",...,514,0,0,0,0,0,NaN,NaN,NaN,NaN
18,앱클론,174900,2018-02-14 10:00,"55,100",2018-02-14 09:10,"54,300",0,"54,300","54,200","6,199",...,25,1,1,19,0,0,NaN,NaN,NaN,NaN
19,디에이치피코리아,131030,2018-02-14 10:00,"10,550",2018-02-14 09:10,"10,400",350,"10,450","10,400","44,083",...,206,3,3,337,1,0,NaN,NaN,NaN,NaN
20,지스마트글로벌,114570,2018-02-14 10:00,"13,700",2018-02-14 09:10,"13,850",650,"13,900","13,850","65,403",...,"4,308",10,8,2295,21,18,NaN,NaN,NaN,NaN
21,씨케이에이치,900120,2018-02-14 10:00,841,2018-02-14 09:10,846,1,852,846,"3,602",...,"20,853",4,4,357,6,2,NaN,NaN,NaN,NaN
22,삼우엠스,082660,2018-02-14 10:00,836,2018-02-14 09:10,828,12,828,816,"11,173",...,"1,391",1,1,49,1,0,NaN,NaN,NaN,NaN
23,인트론바이오,048530,2018-02-14 10:00,"38,300",2018-02-14 09:10,"37,650",-100,"37,650","37,600","6,363",...,81,2,2,263,1,2,NaN,NaN,NaN,NaN
24,휴온스,243070,2018-02-14 10:00,"95,100",2018-02-14 09:10,"94,000","1,900","94,100","94,000","2,291",...,9,0,0,0,0,0,NaN,NaN,NaN,NaN
25,알서포트,131370,2018-02-14 10:00,"2,720",2018-02-14 09:10,"2,730",35,"2,735","2,730","27,044",...,10,0,0,0,0,0,NaN,NaN,NaN,NaN
26,에스에너지,095910,2018-02-14 10:00,"6,670",2018-02-14 09:10,"6,710",50,"6,710","6,660",589,...,32,1,1,31,0,0,NaN,NaN,NaN,NaN
27,키움증권,039490,2018-02-14 10:00,"106,500",2018-02-14 09:10,"106,000",500,"106,000","105,500","2,585",...,144,0,0,0,0,0,NaN,NaN,NaN,NaN
28,녹십자셀,031390,2018-02-14 10:00,"50,700",2018-02-14 09:10,"49,750",-250,"49,800","49,750","9,144",...,104,4,4,168,5,2,NaN,NaN,NaN,NaN
29,성광벤드,014620,2018-02-14 10:00,"12,050",2018-02-14 09:10,"12,200",150,"12,250","12,200","6,521",...,599,0,0,0,0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,에이프로젠제약,003060,2018-02-14 15:30,"4,290",2018-02-14 14:40,"4,285",20,"4,285","4,280","643,221",...,874,79,31,18776,208,92,NaN,NaN,NaN,NaN
703,지니언스,263860,2018-02-14 15:30,"13,550",2018-02-14 14:40,"13,700",0,"13,700","13,650","32,117",...,1,5,4,422,1,1,NaN,NaN,NaN,NaN
704,이녹스첨단소재,272290,2018-02-14 15:30,"68,700",2018-02-14 14:40,"67,800","3,100","67,900","67,800","83,597",...,970,4,4,1459,5,1,NaN,NaN,NaN,NaN
705,KG ETS,151860,2018-02-14 15:30,"4,080",2018-02-14 14:40,"4,105",35,"4,105","4,100","53,759",...,15,0,0,0,0,0,NaN,NaN,NaN,NaN
706,삼기오토모티브,122350,2018-02-14 15:30,"3,470",2018-02-14 14:40,"3,445",-35,"3,450","3,445","68,110",...,209,2,2,148,2,1,NaN,NaN,NaN,NaN
707,현대로템,064350,2018-02-14 15:30,"15,000",2018-02-14 14:40,"15,000",0,"15,000","14,950","139,131",...,172,5,5,1110,19,6,NaN,NaN,NaN,NaN
708,서진오토모티브,122690,2018-02-14 15:30,"4,020",2018-02-14 14:40,"4,050",-25,"4,050","4,005","25,026",...,1,3,3,419,4,5,NaN,NaN,NaN,NaN
709,삼본정밀전자,111870,2018-02-14 15:30,"10,200",2018-02-14 14:40,"10,050",100,"10,050","10,000","9,727",...,50,6,4,255,10,0,NaN,NaN,NaN,NaN
710,테라젠이텍스,066700,2018-02-14 15:30,"10,950",2018-02-14 14:40,"10,950",350,"10,950","10,900","354,231",...,"3,037",24,18,6574,39,24,NaN,NaN,NaN,NaN
711,이오테크닉스,039030,2018-02-14 15:30,"86,700",2018-02-14 14:40,"85,400","1,400","85,600","85,400","59,893",...,148,6,6,710,4,7,NaN,NaN,NaN,NaN
712,이화전기,024810,2018-02-14 15:30,367,2018-02-14 14:40,368,0,368,367,"9,591,966",...,"1,011",51,37,15317,124,95,NaN,NaN,NaN,NaN
713,한온시스템,018880,2018-02-14 15:30,"12,050",2018-02-14 14:40,"11,950",150,"12,000","11,950","415,811",...,162,3,3,1768,4,8,NaN,NaN,NaN,NaN
714,신송홀딩스,006880,2018-02-14 15:30,"6,110",2018-02-14 14:40,"6,100",50,"6,100","6,050","13,061",...,3,1,1,27,2,0,NaN,NaN,NaN,NaN
715,락앤락,115390,2018-02-14 15:30,"23,150",2018-02-14 14:40,"23,150",-150,"23,200","23,150","162,730",...,527,10,8,2984,24,10,NaN,NaN,NaN,NaN
716,메디포스트,078160,2018-02-14 15:30,"100,400",2018-02-14 14:40,"99,800",700,"99,800","99,700","108,844",...,752,26,16,8924,71,25,NaN,NaN,NaN,NaN
717,SK디스커버리,006120,2018-02-14 15:30,"49,150",2018-02-14 14:40,"48,900",-200,"48,950","48,900","40,304",...,94,1,1,152,7,0,NaN,NaN,NaN,NaN
718,테라세미콘,123100,2018-02-14 15:30,"27,350",2018-02-14 14:40,"27,300","1,600","27,350","27,300","252,529",...,"1,800",22,15,5876,51,31,NaN,NaN,NaN,NaN
719,지엠비코리아,013870,2018-02-14 15:30,"8,730",2018-02-14 14:40,"8,710",0,"8,720","8,710","160,144",...,"2,232",7,6,907,8,3,NaN,NaN,NaN,NaN
720,대원산업,005710,2018-02-14 15:30,"8,070",2018-02-14 14:40,"8,190",-250,"8,200","8,180","18,759",...,367,1,1,124,2,0,NaN,NaN,NaN,NaN
721,바디텍메드,206640,2018-02-14 15:30,"18,700",2018-02-14 14:40,"18,400",200,"18,450","18,400","81,798",...,110,3,3,1172,8,7,NaN,NaN,NaN,NaN
722,한국금융지주,071050,2018-02-14 15:30,"79,900",2018-02-14 14:40,"79,900",-100,"79,900","79,800","196,165",...,578,2,2,556,5,0,NaN,NaN,NaN,NaN
723,현대비앤지스틸,004560,2018-02-14 15:30,"12,700",2018-02-14 14:40,"12,600",400,"12,600","12,550","41,995",...,206,2,2,220,2,1,NaN,NaN,NaN,NaN
724,동양,001520,2018-02-14 15:30,"2,020",2018-02-14 14:40,"2,025",-25,"2,030","2,025","353,622",...,79,6,6,1766,47,9,NaN,NaN,NaN,NaN
725,네오위즈,095660,2018-02-14 15:30,"14,100",2018-02-14 14:40,"13,950",-50,"14,000","13,950","113,792",...,93,21,12,4661,59,25,NaN,NaN,NaN,NaN
726,세아베스틸,001430,2018-02-14 15:30,"27,650",2018-02-14 14:40,"27,500",-850,"27,500","27,450","64,402",...,87,4,3,194,4,3,NaN,NaN,NaN,NaN
727,세운메디칼,100700,2018-02-14 15:30,"4,610",2018-02-14 14:40,"4,615",-60,"4,625","4,610","296,115",...,"1,018",3,3,477,3,4,NaN,NaN,NaN,NaN
728,디에스티로봇,090710,2018-02-14 15:30,"2,455",2018-02-14 14:40,"2,470",55,"2,480","2,470","1,326,390",...,"1,016",23,18,4997,20,14,NaN,NaN,NaN,NaN
729,엘엠에스,073110,2018-02-14 15:30,"8,650",2018-02-14 14:40,"8,650",140,"8,650","8,620","8,267",...,5,3,3,258,5,1,NaN,NaN,NaN,NaN
730,옵트론텍,082210,2018-02-14 15:30,"7,480",2018-02-14 14:40,"7,490",220,"7,490","7,480","197,732",...,928,4,4,1203,4,6,NaN,NaN,NaN,NaN
731,한컴MDS,086960,2018-02-14 15:30,"18,350",2018-02-14 14:40,"18,350",-350,"18,400","18,300","63,042",...,2,3,3,538,9,4,NaN,NaN,NaN,NaN

In [68]:
for index, row in total.iterrows():
    mkt_cap = MKT_CAP[row["code"]]
    if row["code"] in KOSPI:
        kospi = 1
    else:
        kospi = 0
    
    if row["code"] in KOSDAQ:
        kosdaq = 1
    else:
        kosdaq = 0
        
    if row["code"] in TRASH:
        trash = 1
    else:
        trash = 0
    total.set_value(index,'mkt_cap', mkt_cap)
    total.set_value(index,'kospi', kospi)
    total.set_value(index,'kosdaq', kosdaq)
    total.set_value(index,'trash', trash)

In [71]:
total

,name,code,time,price,time_1,price_1,price_dif_1,sell_1,buy_1,volume_1,...,variation_3,post_num_3,unique_id_3,click_3,like_3,dislike_3,mkt_cap,kospi,kosdaq,trash
0,호텔신라,008770,2018-02-14 10:00,"83,400",2018-02-14 09:10,"84,700","1,800","84,800","84,700","29,336",...,"2,036",5,4,571,7,4,32419.0,1.0,0.0,0.0
1,대한광통신,010170,2018-02-14 10:00,"7,050",2018-02-14 09:10,"7,060",90,"7,060","7,050","101,713",...,"3,467",3,3,142,1,3,4176.0,0.0,1.0,0.0
2,포스코 ICT,022100,2018-02-14 10:00,"8,320",2018-02-14 09:10,"8,310",0,"8,330","8,310","44,311",...,"1,712",3,3,781,1,5,12953.0,0.0,1.0,0.0
3,한화케미칼,009830,2018-02-14 10:00,"32,350",2018-02-14 09:10,"32,700",550,"32,700","32,650","32,647",...,"3,102",6,6,706,3,8,55706.0,1.0,0.0,0.0
4,지엘팜텍,204840,2018-02-14 10:00,"4,760",2018-02-14 09:10,"4,680",50,"4,700","4,680","114,565",...,"2,844",4,4,970,8,12,1494.0,0.0,1.0,0.0
5,코웰패션,033290,2018-02-14 10:00,"5,350",2018-02-14 09:10,"5,270",90,"5,280","5,270","22,780",...,"1,530",1,1,121,1,0,4661.0,0.0,1.0,0.0
6,대한항공,003490,2018-02-14 10:00,"35,900",2018-02-14 09:10,"35,700",300,"35,750","35,700","7,560",...,"1,028",2,2,70,0,0,33338.0,1.0,0.0,0.0
7,대한뉴팜,054670,2018-02-14 10:00,"13,750",2018-02-14 09:10,"13,800",0,"13,800","13,750","2,556",...,365,1,1,64,3,3,2117.0,0.0,1.0,0.0
8,레드캡투어,038390,2018-02-14 10:00,"15,350",2018-02-14 09:10,"15,350",100,"15,350","15,200",7,...,1,0,0,0,0,0,1357.0,0.0,1.0,0.0
9,이마트,139480,2018-02-14 10:00,"290,000",2018-02-14 09:10,"283,500","5,000","284,000","283,500","8,469",...,75,1,1,23,2,0,86415.0,1.0,0.0,0.0
10,녹십자,006280,2018-02-14 10:00,"204,500",2018-02-14 09:10,"201,000","1,500","201,000","200,000",910,...,581,1,1,175,3,0,25301.0,1.0,0.0,0.0
11,GS,078930,2018-02-14 10:00,"63,000",2018-02-14 09:10,"62,600",100,"62,700","62,600","2,353",...,219,1,1,156,3,0,623.0,1.0,0.0,0.0
12,CJ헬로,037560,2018-02-14 10:00,"8,980",2018-02-14 09:10,"8,650",230,"8,650","8,640","22,839",...,"2,134",2,2,129,1,1,7466.0,1.0,0.0,0.0
13,모토닉,009680,2018-02-14 10:00,"10,150",2018-02-14 09:10,"10,300",50,"10,300","10,200","1,289",...,50,0,0,0,0,0,3333.0,1.0,0.0,0.0
14,AJ렌터카,068400,2018-02-14 10:00,"10,500",2018-02-14 09:10,"10,400",0,"10,550","10,400","22,181",...,3,2,2,163,6,1,2480.0,1.0,0.0,0.0
15,한국전자홀딩스,006200,2018-02-14 10:00,799,2018-02-14 09:10,795,-3,795,793,203,...,"1,979",0,0,0,0,0,378.0,1.0,0.0,0.0
16,일진머티리얼즈,020150,2018-02-14 10:00,"32,300",2018-02-14 09:10,"32,300",350,"32,250","32,200","11,043",...,724,16,9,2871,36,38,15732.0,1.0,0.0,0.0
17,코위버,056360,2018-02-14 10:00,"7,790",2018-02-14 09:10,"7,870",120,"7,890","7,870","9,193",...,514,0,0,0,0,0,784.0,0.0,1.0,0.0
18,앱클론,174900,2018-02-14 10:00,"55,100",2018-02-14 09:10,"54,300",0,"54,300","54,200","6,199",...,25,1,1,19,0,0,4039.0,0.0,1.0,0.0
19,디에이치피코리아,131030,2018-02-14 10:00,"10,550",2018-02-14 09:10,"10,400",350,"10,450","10,400","44,083",...,206,3,3,337,1,0,1714.0,0.0,1.0,0.0
20,지스마트글로벌,114570,2018-02-14 10:00,"13,700",2018-02-14 09:10,"13,850",650,"13,900","13,850","65,403",...,"4,308",10,8,2295,21,18,2942.0,0.0,1.0,0.0
21,씨케이에이치,900120,2018-02-14 10:00,841,2018-02-14 09:10,846,1,852,846,"3,602",...,"20,853",4,4,357,6,2,961.0,0.0,1.0,0.0
22,삼우엠스,082660,2018-02-14 10:00,836,2018-02-14 09:10,828,12,828,816,"11,173",...,"1,391",1,1,49,1,0,345.0,0.0,1.0,0.0
23,인트론바이오,048530,2018-02-14 10:00,"38,300",2018-02-14 09:10,"37,650",-100,"37,650","37,600","6,363",...,81,2,2,263,1,2,6060.0,0.0,1.0,0.0
24,휴온스,243070,2018-02-14 10:00,"95,100",2018-02-14 09:10,"94,000","1,900","94,100","94,000","2,291",...,9,0,0,0,0,0,5874.0,0.0,1.0,0.0
25,알서포트,131370,2018-02-14 10:00,"2,720",2018-02-14 09:10,"2,730",35,"2,735","2,730","27,044",...,10,0,0,0,0,0,1518.0,0.0,1.0,0.0
26,에스에너지,095910,2018-02-14 10:00,"6,670",2018-02-14 09:10,"6,710",50,"6,710","6,660",589,...,32,1,1,31,0,0,900.0,0.0,1.0,0.0
27,키움증권,039490,2018-02-14 10:00,"106,500",2018-02-14 09:10,"106,000",500,"106,000","105,500","2,585",...,144,0,0,0,0,0,23315.0,1.0,0.0,0.0
28,녹십자셀,031390,2018-02-14 10:00,"50,700",2018-02-14 09:10,"49,750",-250,"49,800","49,750","9,144",...,104,4,4,168,5,2,6444.0,0.0,1.0,0.0
29,성광벤드,014620,2018-02-14 10:00,"12,050",2018-02-14 09:10,"12,200",150,"12,250","12,200","6,521",...,599,0,0,0,0,0,3718.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,에이프로젠제약,003060,2018-02-14 15:30,"4,290",2018-02-14 14:40,"4,285",20,"4,285","4,280","643,221",...,874,79,31,18776,208,92,3882.0,1.0,0.0,0.0
703,지니언스,263860,2018-02-14 15:30,"13,550",2018-02-14 14:40,"13,700",0,"13,700","13,650","32,117",...,1,5,4,422,1,1,694.0,0.0,1.0,0.0
704,이녹스첨단소재,272290,2018-02-14 15:30,"68,700",2018-02-14 14:40,"67,800","3,100","67,900","67,800","83,597",...,970,4,4,1459,5,1,6315.0,0.0,1.0,0.0
705,KG ETS,151860,2018-02-14 15:30,"4,080",2018-02-14 14:40,"4,105",35,"4,105","4,100","53,759",...,15,0,0,0,0,0,1469.0,0.0,1.0,0.0
706,삼기오토모티브,122350,2018-02-14 15:30,"3,470",2018-02-14 14:40,"3,445",-35,"3,450","3,445","68,110",...,209,2,2,148,2,1,1093.0,0.0,1.0,0.0
707,현대로템,064350,2018-02-14 15:30,"15,000",2018-02-14 14:40,"15,000",0,"15,000","14,950","139,131",...,172,5,5,1110,19,6,13175.0,1.0,0.0,0.0
708,서진오토모티브,122690,2018-02-14 15:30,"4,020",2018-02-14 14:40,"4,050",-25,"4,050","4,005","25,026",...,1,3,3,419,4,5,783.0,0.0,1.0,0.0
709,삼본정밀전자,111870,2018-02-14 15:30,"10,200",2018-02-14 14:40,"10,050",100,"10,050","10,000","9,727",...,50,6,4,255,10,0,960.0,0.0,1.0,0.0
710,테라젠이텍스,066700,2018-02-14 15:30,"10,950",2018-02-14 14:40,"10,950",350,"10,950","10,900","354,231",...,"3,037",24,18,6574,39,24,3735.0,0.0,1.0,0.0
711,이오테크닉스,039030,2018-02-14 15:30,"86,700",2018-02-14 14:40,"85,400","1,400","85,600","85,400","59,893",...,148,6,6,710,4,7,1524.0,0.0,1.0,0.0
712,이화전기,024810,2018-02-14 15:30,367,2018-02-14 14:40,368,0,368,367,"9,591,966",...,"1,011",51,37,15317,124,95,1325.0,0.0,1.0,0.0
713,한온시스템,018880,2018-02-14 15:30,"12,050",2018-02-14 14:40,"11,950",150,"12,000","11,950","415,811",...,162,3,3,1768,4,8,67793.0,1.0,0.0,0.0
714,신송홀딩스,006880,2018-02-14 15:30,"6,110",2018-02-14 14:40,"6,100",50,"6,100","6,050","13,061",...,3,1,1,27,2,0,736.0,1.0,0.0,0.0
715,락앤락,115390,2018-02-14 15:30,"23,150",2018-02-14 14:40,"23,150",-150,"23,200","23,150","162,730",...,527,10,8,2984,24,10,13228.0,1.0,0.0,0.0
716,메디포스트,078160,2018-02-14 15:30,"100,400",2018-02-14 14:40,"99,800",700,"99,800","99,700","108,844",...,752,26,16,8924,71,25,8228.0,0.0,1.0,0.0
717,SK디스커버리,006120,2018-02-14 15:30,"49,150",2018-02-14 14:40,"48,900",-200,"48,950","48,900","40,304",...,94,1,1,152,7,0,5203.0,1.0,0.0,0.0
718,테라세미콘,123100,2018-02-14 15:30,"27,350",2018-02-14 14:40,"27,300","1,600","27,350","27,300","252,529",...,"1,800",22,15,5876,51,31,3126.0,0.0,1.0,0.0
719,지엠비코리아,013870,2018-02-14 15:30,"8,730",2018-02-14 14:40,"8,710",0,"8,720","8,710","160,144",...,"2,232",7,6,907,8,3,1791.0,1.0,0.0,0.0
720,대원산업,005710,2018-02-14 15:30,"8,070",2018-02-14 14:40,"8,190",-250,"8,200","8,180","18,759",...,367,1,1,124,2,0,1645.0,0.0,1.0,0.0
721,바디텍메드,206640,2018-02-14 15:30,"18,700",2018-02-14 14:40,"18,400",200,"18,450","18,400","81,798",...,110,3,3,1172,8,7,4509.0,0.0,1.0,0.0
722,한국금융지주,071050,2018-02-14 15:30,"79,900",2018-02-14 14:40,"79,900",-100,"79,900","79,800","196,165",...,578,2,2,556,5,0,45584.0,1.0,0.0,0.0
723,현대비앤지스틸,004560,2018-02-14 15:30,"12,700",2018-02-14 14:40,"12,600",400,"12,600","12,550","41,995",...,206,2,2,220,2,1,1938.0,1.0,0.0,0.0
724,동양,001520,2018-02-14 15:30,"2,020",2018-02-14 14:40,"2,025",-25,"2,030","2,025","353,622",...,79,6,6,1766,47,9,4881.0,1.0,0.0,0.0
725,네오위즈,095660,2018-02-14 15:30,"14,100",2018-02-14 14:40,"13,950",-50,"14,000","13,950","113,792",...,93,21,12,4661,59,25,3123.0,0.0,1.0,0.0
726,세아베스틸,001430,2018-02-14 15:30,"27,650",2018-02-14 14:40,"27,500",-850,"27,500","27,450","64,402",...,87,4,3,194,4,3,9880.0,1.0,0.0,0.0
727,세운메디칼,100700,2018-02-14 15:30,"4,610",2018-02-14 14:40,"4,615",-60,"4,625","4,610","296,115",...,"1,018",3,3,477,3,4,2085.0,0.0,1.0,0.0
728,디에스티로봇,090710,2018-02-14 15:30,"2,455",2018-02-14 14:40,"2,470",55,"2,480","2,470","1,326,390",...,"1,016",23,18,4997,20,14,1437.0,0.0,1.0,0.0
729,엘엠에스,073110,2018-02-14 15:30,"8,650",2018-02-14 14:40,"8,650",140,"8,650","8,620","8,267",...,5,3,3,258,5,1,776.0,0.0,1.0,0.0
730,옵트론텍,082210,2018-02-14 15:30,"7,480",2018-02-14 14:40,"7,490",220,"7,490","7,480","197,732",...,928,4,4,1203,4,6,1744.0,0.0,1.0,0.0
731,한컴MDS,086960,2018-02-14 15:30,"18,350",2018-02-14 14:40,"18,350",-350,"18,400","18,300","63,042",...,2,3,3,538,9,4,1659.0,0.0,1.0,0.0