In [1]:
import pandas as pd
import numpy as np
import json
import re

In [2]:
def open_files(date):
    focus_text = "2018-02-" + date + "_focus/2018-02-" + \
                 date + "_focus_group.json"
    krx_text = "krx_code.json"
    price_text = "2018-02-" + date + "_price_no_constraint.json"
    
    with open(focus_text, 'r', encoding='UTF-8') as focus_group:
        focus = json.load(focus_group)
    with open(krx_text, 'r', encoding='UTF-8') as krx:
        krx_code = json.load(krx)
    with open(price_text, 'r', encoding='UTF-8') as pnc:
        price = json.load(pnc)
    
    return focus, krx_code, price

In [3]:
def get_time_disc(date):
    
    time = []
    prefix = "2018-02-" + date + "_focus/discussion_2018-02-" + date
    
    for hour in range(9,16):
        
        if date == "26" and hour == 9:
            continue
        
        elif date == "27" and hour == 11:
            continue
            
        for minute in range(0, 6):
            if date == "26" and hour == 10 and minute == 0:
                continue
            
            elif date == "27" and hour == 10 and minute > 2:
                continue
            
            elif date == "27" and hour == 12 and minute < 3:
                continue
            
            time.append(prefix + " " + (("0" + str(hour)) if hour <= 9 else str(hour))+ \
                        ":" + str(minute) + "0.json")
            
            if hour == 15 and minute > 3:
                del time[len(time) - 1]
    
    return time

In [4]:
def df_list_dis(date):
    df_list = []
    time = get_time_disc(date)
    for x in time:
        with open(x, 'r', encoding='UTF-8') as f:
            discussion = json.load(f)        
            discuss_df = pd.DataFrame(discussion, columns = ["post_num", \
                                "unique_id", "click", "like", "dislike", 
                                "name", "time"])
            reset_col = ["name", "time", "post_num", "unique_id", "click", \
                         "like", "dislike"]
            discuss_df = discuss_df[reset_col]
            df_list.append(discuss_df)
    return df_list

In [5]:
#half an hour low freq
'''
def list_to_df(date, df_list, column_names, key_list):
    total = pd.DataFrame(columns=column_names)
    for ind, df in enumerate(df_list):
        if ((ind + 1) % 3  == 0) and (ind != 2):
            df_total = df.merge(df_list[ind - 5], on = \
                                key_list).merge(df_list[ind - 4], \
                                on = key_list).merge(df_list[ind - 3], on = key_list)
            df_total.columns = column_names
            total = pd.concat([total, df_total], axis = 0) 
    
    return total  
'''

'\ndef list_to_df(date, df_list, column_names, key_list):\n    total = pd.DataFrame(columns=column_names)\n    for ind, df in enumerate(df_list):\n        if ((ind + 1) % 3  == 0) and (ind != 2):\n            df_total = df.merge(df_list[ind - 5], on =                                 key_list).merge(df_list[ind - 4],                                 on = key_list).merge(df_list[ind - 3], on = key_list)\n            df_total.columns = column_names\n            total = pd.concat([total, df_total], axis = 0) \n    \n    return total  \n'

In [6]:
#half an hour high freq
'''
def list_to_df(date, df_list, column_names, key_list):
    total = pd.DataFrame(columns=column_names)
    for ind, df in enumerate(df_list):
        if ind >= 5:
            df_total = df.merge(df_list[ind - 5], on = \
                                key_list).merge(df_list[ind - 4], \
                                on = key_list).merge(df_list[ind - 3], on = key_list)
            df_total.columns = column_names
            total = pd.concat([total, df_total], axis = 0)
    
    return total  
'''

'\ndef list_to_df(date, df_list, column_names, key_list):\n    total = pd.DataFrame(columns=column_names)\n    for ind, df in enumerate(df_list):\n        if ind >= 5:\n            df_total = df.merge(df_list[ind - 5], on =                                 key_list).merge(df_list[ind - 4],                                 on = key_list).merge(df_list[ind - 3], on = key_list)\n            df_total.columns = column_names\n            total = pd.concat([total, df_total], axis = 0)\n    \n    return total  \n'

In [7]:
#ten min low freq
'''
def list_to_df(date, df_list, column_names, key_list):

    total = pd.DataFrame(columns=column_names)
    if date not in ['26', '27']:
        for ind, df in enumerate(df_list):
            if (ind % 3 == 0) and (ind != 0):
                df_total = df.merge(df_list[ind - 3], on = \
                                    key_list).merge(df_list[ind - 2], \
                                    on = key_list).merge(df_list[ind - 1], on = key_list)
                df_total.columns = column_names
                total = pd.concat([total, df_total], axis = 0)
    elif date == '26':
        
    
    return total
    '''

"\ndef list_to_df(date, df_list, column_names, key_list):\n\n    total = pd.DataFrame(columns=column_names)\n    if date not in ['26', '27']:\n        for ind, df in enumerate(df_list):\n            if (ind % 3 == 0) and (ind != 0):\n                df_total = df.merge(df_list[ind - 3], on =                                     key_list).merge(df_list[ind - 2],                                     on = key_list).merge(df_list[ind - 1], on = key_list)\n                df_total.columns = column_names\n                total = pd.concat([total, df_total], axis = 0)\n    elif date == '26':\n        \n    \n    return total\n    "

In [8]:
#ten min high freq
def list_to_df(date, df_list, column_names, key_list):
    total = pd.DataFrame(columns=column_names)
    for ind, df in enumerate(df_list):
        if ind >= 3:
            df_total = df.merge(df_list[ind - 3], on = \
                                key_list).merge(df_list[ind - 2], \
                                on = key_list).merge(df_list[ind - 1], on = key_list)
            df_total.columns = column_names
            total = pd.concat([total, df_total], axis = 0)
    
    return total

In [9]:
COLUMN_DISC =["name", "time", "post_num", "unique_id", "click", \
              "like", "dislike", "time_1", "post_num_1", "unique_id_1", "click_1", \
              "like_1", "dislike_1", "time_2", "post_num_2", "unique_id_2", "click_2", \
              "like_2", "dislike_2", "time_3", "post_num_3", "unique_id_3", "click_3", \
              "like_3", "dislike_3"]

def get_discuss_df(date):
    discussion_list = df_list_dis(date)
    discuss_df = list_to_df(date, discussion_list, COLUMN_DISC, 
                            ['name']).reset_index().drop(["index"], axis = 1)
    return discuss_df

In [10]:
def df_list_price(date):
    price_df = pd.DataFrame(price, columns = ["index", "code", "name", "time", "price", \
                                         "price_dif", "sell", "buy", "volume", "variation"])
    price_df = price_df[["code", "name", "time", "price", \
                    "price_dif", "sell", "buy", "volume", "variation"]][1:]
    text = "2018-02-" + date + " 09:00"
    price_df = price_df[price_df["time"] != text]
    time_list = price_df['time'].unique().tolist()
    price_df_list = []
    for time in time_list:
        df = price_df[price_df["time"] == time]
        df = df[["code", "name", "time", "price", \
                "price_dif", "sell", "buy", "volume", "variation"]]
        price_df_list.append(df)
        
    return price_df_list

In [11]:
COLUMN_PRICE=["code", "name", "time", "price", "price_dif", "sell", 
              "buy", "volume", "variation", "time_1", "price_1", 
              "price_dif_1", "sell_1", "buy_1", "volume_1", "variation_1",
              "time_2", "price_2", "price_dif_2", "sell_2", "buy_2", 
              "volume_2", "variation_2", "time_3", "price_3", 
              "price_dif_3", "sell_3", "buy_3", "volume_3", "variation_3"]

def get_price_df(date):
    price_df_list = df_list_price(date)
    price_df = list_to_df(date, price_df_list, COLUMN_PRICE, \
                          ['code', 'name']).reset_index().drop(["index"], axis = 1)
    
    return price_df

In [12]:
COLUMN_TOTAL = ['name', 'code', 'time', 'price', 'time_1', "price_1", \
                "price_dif_1", "sell_1", "buy_1", "volume_1", "variation_1", \
                'post_num_1', 'unique_id_1', 'click_1', 'like_1', 'dislike_1', \
                'time_2', 'price_2', "price_dif_2", "sell_2", "buy_2", \
                "volume_2", "variation_2", 'post_num_2', 'unique_id_2', 'click_2', \
                'like_2', 'dislike_2', 'time_3', 'price_3', "price_dif_3", \
                "sell_3", "buy_3", "volume_3", "variation_3", 'post_num_3', \
                'unique_id_3', 'click_3', 'like_3', 'dislike_3']

def get_total_df(date):
    price_df = get_price_df(date)
    discuss_df = get_discuss_df(date)
    total_df = pd.merge(price_df, discuss_df, on = ['name', \
                                                    'time', 'time_1', 'time_2', 'time_3'])
    total_df = total_df[COLUMN_TOTAL]
    
    return total_df

In [13]:
import numpy as np
import re

with open("company_size.json", 'r', encoding='UTF-8') as f:
    company_size = json.load(f)

company_df = pd.DataFrame({"company_name": np.zeros(0), \
                           "code": np.zeros(0), "market": np.zeros(0), 
                          "company_size": np.zeros(0)})

company_df = pd.DataFrame(company_size, columns = ["name", "code", "market", "size"])

KOSPI = []
KOSDAQ = []
TRASH = []
MKT_CAP = {}

for idx, row in company_df.iterrows():
    if re.sub('[0-9 ,위]', '', row["market"]) == "코스피":
        KOSPI.append(row["code"])
    elif re.sub('[0-9 ,위]', '', row["market"]) == "코스닥":
        KOSDAQ.append(row["code"])
    else:
        TRASH.append(row["code"])
    
    MKT_CAP[row["code"]] = int(re.sub('[조억원,]', '', row["size"]))

In [14]:
def add_company(date):
    
    total = get_total_df(date)
    total["mkt_cap"] = np.nan
    total["kospi"] = np.nan
    total["kosdaq"] = np.nan
    total["trash"] = np.nan
    
    for index, row in total.iterrows():
        mkt_cap = MKT_CAP[row["code"]]
        if row["code"] in KOSPI:
            kospi = 1
        else:
            kospi = 0

        if row["code"] in KOSDAQ:
            kosdaq = 1
        else:
            kosdaq = 0

        if row["code"] in TRASH:
            trash = 1
        else:
            trash = 0
        total.set_value(index,'mkt_cap', mkt_cap)
        total.set_value(index,'kospi', kospi)
        total.set_value(index,'kosdaq', kosdaq)
        total.set_value(index,'trash', trash)  
    
    return total

In [15]:
def transform_df(date):
    
    total = add_company(date)
    total.dropna(inplace = True)
    var_to_transform = ['price', 'price_1', 'price_dif_1', 'sell_1', 
                        'buy_1', 'volume_1', 'variation_1', 'price_2', 
                        'price_dif_2', 'sell_2', 'buy_2', 'volume_2', 
                        'variation_2', 'price_3', 'price_dif_3', 'sell_3', 'buy_3', 
                        'volume_3', 'variation_3']
    for var in var_to_transform:
        total = total[total[var] != '\xa0']
        for index, row in total.iterrows():
            if isinstance(row[var], str):
                data = row[var].split(",")
                value = ''.join(data)
                value = int(value)
                total.set_value(index, var, value)
    return total

In [16]:
focus, krx_code, price = open_files('21')
total_21 = transform_df('21')
focus, krx_code, price = open_files('22')
total_22 = transform_df('22')
focus, krx_code, price = open_files('23')
total_23 = transform_df('23')
focus, krx_code, price = open_files('26')
total_26 = transform_df('26')
focus, krx_code, price = open_files('27')
total_27 = transform_df('27')
focus, krx_code, price = open_files('28')
total_28 = transform_df('28')

In [17]:
total_df = pd.concat([total_21, total_22, total_23, total_26, total_27, total_28])

In [18]:
total_df

,name,code,time,price,time_1,price_1,price_dif_1,sell_1,buy_1,volume_1,...,variation_3,post_num_3,unique_id_3,click_3,like_3,dislike_3,mkt_cap,kospi,kosdaq,trash
0,크리스탈,083790,2018-02-21 09:40,27500,2018-02-21 09:10,26800,-100,26850,26800,18097,...,2390,14,11,5591,103,63,6709.0,0.0,1.0,0.0
1,LG유플러스,032640,2018-02-21 09:40,12900,2018-02-21 09:10,13000,0,13000,12950,146579,...,18056,7,7,591,11,3,55668.0,1.0,0.0,0.0
2,마크로젠,038290,2018-02-21 09:40,48300,2018-02-21 09:10,47100,0,47100,47050,10608,...,7569,1,1,238,1,2,5070.0,0.0,1.0,0.0
3,LS산전,010120,2018-02-21 09:40,58200,2018-02-21 09:10,57800,200,57800,57600,2835,...,248,5,3,288,2,1,17340.0,1.0,0.0,0.0
4,CJ,001040,2018-02-21 09:40,163000,2018-02-21 09:10,161500,-1000,162000,161500,2440,...,87,1,1,73,0,0,49017.0,1.0,0.0,0.0
5,홈캐스트,064240,2018-02-21 09:40,12900,2018-02-21 09:10,12700,50,12700,12650,23346,...,1924,6,6,1350,4,9,4076.0,0.0,1.0,0.0
6,한국콜마홀딩스,024720,2018-02-21 09:40,47500,2018-02-21 09:10,50200,4100,50300,50200,176091,...,2202,16,12,2763,7,13,7579.0,1.0,0.0,0.0
7,에이프로젠제약,003060,2018-02-21 09:40,4500,2018-02-21 09:10,4465,15,4470,4465,51527,...,7697,7,7,2769,8,3,3882.0,1.0,0.0,0.0
8,대한항공,003490,2018-02-21 09:40,35700,2018-02-21 09:10,35300,-100,35300,35250,10548,...,1186,1,1,308,3,5,33338.0,1.0,0.0,0.0
9,KD건설,044180,2018-02-21 09:40,171,2018-02-21 09:10,172,-1,172,171,3173638,...,221,20,12,2816,42,42,601.0,0.0,1.0,0.0
10,유니온머티리얼,047400,2018-02-21 09:40,2735,2018-02-21 09:10,2685,25,2685,2655,4877,...,3697,0,0,0,0,0,1107.0,1.0,0.0,0.0
11,동양생명,082640,2018-02-21 09:40,7540,2018-02-21 09:10,7500,-60,7500,7490,7763,...,101,1,1,14,0,0,12247.0,1.0,0.0,0.0
12,삼성에스디에스,018260,2018-02-21 09:40,238000,2018-02-21 09:10,235000,500,235000,234500,4211,...,1716,20,6,2401,14,26,194605.0,1.0,0.0,0.0
13,BGF,027410,2018-02-21 09:40,13700,2018-02-21 09:10,13500,50,13550,13500,10787,...,161,8,8,1307,20,11,4275.0,1.0,0.0,0.0
14,효성,004800,2018-02-21 09:40,124500,2018-02-21 09:10,123500,500,123500,123000,1809,...,122,1,1,82,1,2,46179.0,1.0,0.0,0.0
15,큐렉소,060280,2018-02-21 09:40,8740,2018-02-21 09:10,8620,0,8610,8590,8831,...,390,0,0,0,0,0,2693.0,0.0,1.0,0.0
16,유니슨,018000,2018-02-21 09:40,3555,2018-02-21 09:10,3465,-35,3465,3460,38785,...,3860,3,3,1140,8,6,2607.0,0.0,1.0,0.0
17,아모레퍼시픽,090430,2018-02-21 09:40,283500,2018-02-21 09:10,281000,5500,281500,281000,16268,...,883,7,4,2450,22,14,17991.0,1.0,0.0,0.0
18,만도,204320,2018-02-21 09:40,240000,2018-02-21 09:10,239500,5000,239500,239000,2817,...,44,0,0,0,0,0,23526.0,1.0,0.0,0.0
19,아이진,185490,2018-02-21 09:40,21600,2018-02-21 09:10,21700,0,21750,21650,7185,...,9,5,5,641,7,6,2430.0,0.0,1.0,0.0
20,휠라코리아,081660,2018-02-21 09:40,87900,2018-02-21 09:10,88000,500,88000,87800,43,...,17,2,2,94,1,2,11575.0,1.0,0.0,0.0
21,용평리조트,070960,2018-02-21 09:40,8510,2018-02-21 09:10,8460,-30,8490,8460,28183,...,704,18,13,3189,58,25,3971.0,1.0,0.0,0.0
22,바이오스마트,038460,2018-02-21 09:40,6420,2018-02-21 09:10,6370,10,6370,6360,38142,...,5205,5,3,92,0,0,1106.0,0.0,1.0,0.0
23,LG이노텍,011070,2018-02-21 09:40,126500,2018-02-21 09:10,126000,500,126000,125500,19201,...,108,1,1,2,0,0,3531.0,1.0,0.0,0.0
24,캠시스,050110,2018-02-21 09:40,2990,2018-02-21 09:10,3005,55,3010,3005,1206468,...,9344,8,8,3607,64,36,1746.0,0.0,1.0,0.0
25,키움증권,039490,2018-02-21 09:40,105500,2018-02-21 09:10,104000,-500,104000,103500,2597,...,157,3,3,446,4,4,23315.0,1.0,0.0,0.0
26,SK케미칼,285130,2018-02-21 09:40,110500,2018-02-21 09:10,109000,-500,110000,109500,2172,...,10,4,4,924,4,9,13143.0,1.0,0.0,0.0
27,액션스퀘어,205500,2018-02-21 09:40,8460,2018-02-21 09:10,8480,10,8500,8480,36783,...,1659,40,32,10394,66,29,2139.0,0.0,1.0,0.0
28,SKC코오롱PI,178920,2018-02-21 09:40,41250,2018-02-21 09:10,40950,800,40950,40900,27890,...,1433,4,4,995,7,8,11570.0,0.0,1.0,0.0
29,톱텍,108230,2018-02-21 09:40,29850,2018-02-21 09:10,29000,-100,29150,29050,17478,...,1302,4,4,601,9,7,1968.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4686,삼진엘앤디,054090,2018-02-28 15:30,2470,2018-02-28 15:00,2490,-20,2490,2465,87759,...,1,0,0,0,0,0,628.0,0.0,1.0,0.0
4687,한전KPS,051600,2018-02-28 15:30,40350,2018-02-28 15:00,40450,-200,40500,40450,62721,...,255,5,5,517,0,2,18788.0,1.0,0.0,0.0
4688,조아제약,034940,2018-02-28 15:30,5580,2018-02-28 15:00,5600,-250,5610,5600,673986,...,2578,21,12,3990,57,40,1625.0,0.0,1.0,0.0
4689,대주전자재료,078600,2018-02-28 15:30,14900,2018-02-28 15:00,14900,-1150,14900,14850,295112,...,212,3,3,1430,1,7,2401.0,0.0,1.0,0.0
4690,디스플레이텍,066670,2018-02-28 15:30,3790,2018-02-28 15:00,3760,-45,3760,3735,18341,...,691,0,0,0,0,0,712.0,0.0,1.0,0.0
4691,지어소프트,051160,2018-02-28 15:30,2060,2018-02-28 15:00,2065,20,2065,2055,109990,...,1,1,1,66,1,0,288.0,0.0,1.0,0.0
4692,아세아제지,002310,2018-02-28 15:30,24150,2018-02-28 15:00,24150,850,24150,24050,53783,...,1,0,0,0,0,0,1948.0,1.0,0.0,0.0
4693,세아베스틸,001430,2018-02-28 15:30,28500,2018-02-28 15:00,28450,450,28500,28450,61598,...,245,1,1,129,0,0,9880.0,1.0,0.0,0.0
4694,코라오홀딩스,900140,2018-02-28 15:30,4680,2018-02-28 15:00,4685,-15,4685,4680,111182,...,588,7,6,1108,19,18,2288.0,1.0,0.0,0.0
4695,에스앤씨엔진그룹,900080,2018-02-28 15:30,959,2018-02-28 15:00,960,-8,960,959,286613,...,1511,9,7,361,2,3,1117.0,0.0,1.0,0.0
4696,코스맥스비티아이,044820,2018-02-28 15:30,33350,2018-02-28 15:00,33200,-400,33200,33150,9499,...,2,0,0,0,0,0,3198.0,1.0,0.0,0.0
4697,삼지전자,037460,2018-02-28 15:30,12500,2018-02-28 15:00,12400,-100,12400,12350,187338,...,57,6,5,2100,12,11,2154.0,0.0,1.0,0.0
4698,강스템바이오텍,217730,2018-02-28 15:30,12500,2018-02-28 15:00,12250,-600,12250,12200,166081,...,185,10,6,1250,20,5,2004.0,0.0,1.0,0.0
4699,애경유화,161000,2018-02-28 15:30,18200,2018-02-28 15:00,18300,350,18300,18250,91416,...,160,5,3,570,1,1,5719.0,1.0,0.0,0.0
4700,한전산업,130660,2018-02-28 15:30,4005,2018-02-28 15:00,4015,-10,4020,4015,17143,...,1040,1,1,123,0,0,1307.0,1.0,0.0,0.0
4701,쎄트렉아이,099320,2018-02-28 15:30,40900,2018-02-28 15:00,40650,250,40700,40650,27010,...,1,9,8,2617,40,30,1577.0,0.0,1.0,0.0
4702,파트론,091700,2018-02-28 15:30,9330,2018-02-28 15:00,9150,-460,9170,9150,976067,...,16732,45,31,12126,66,45,5659.0,0.0,1.0,0.0
4703,흥구석유,024060,2018-02-28 15:30,2730,2018-02-28 15:00,2745,-30,2745,2740,1936,...,310,0,0,0,0,0,416.0,0.0,1.0,0.0
4704,코오롱인더,120110,2018-02-28 15:30,71100,2018-02-28 15:00,71400,-1800,71400,71300,199868,...,420,22,16,7219,49,37,19014.0,1.0,0.0,0.0
4705,지스마트글로벌,114570,2018-02-28 15:30,13350,2018-02-28 15:00,13350,-450,13400,13350,246022,...,787,19,12,4574,31,23,2942.0,0.0,1.0,0.0
4706,코미팜,041960,2018-02-28 15:30,39000,2018-02-28 15:00,39000,-800,39050,39000,156118,...,838,11,10,3269,33,19,22518.0,0.0,1.0,0.0
4707,대창스틸,140520,2018-02-28 15:30,4165,2018-02-28 15:00,4210,-100,4210,4200,162049,...,180,6,4,832,2,1,859.0,0.0,1.0,0.0
4708,골프존뉴딘,121440,2018-02-28 15:30,6040,2018-02-28 15:00,6090,-110,6100,6090,238004,...,148,6,5,893,2,1,2592.0,0.0,1.0,0.0
4709,테스,095610,2018-02-28 15:30,33450,2018-02-28 15:00,33050,-800,33100,33050,103955,...,100,0,0,0,0,0,6672.0,0.0,1.0,0.0
4710,루트로닉,085370,2018-02-28 15:30,13150,2018-02-28 15:00,13200,-700,13300,13200,235748,...,1126,27,17,9149,75,35,3345.0,0.0,1.0,0.0
4711,이라이콤,041520,2018-02-28 15:30,6860,2018-02-28 15:00,6910,-50,6910,6900,14009,...,150,0,0,0,0,0,861.0,0.0,1.0,0.0
4712,EG,037370,2018-02-28 15:30,10150,2018-02-28 15:00,10250,-700,10300,10250,87397,...,10493,5,4,640,7,7,829.0,0.0,1.0,0.0
4713,신한지주,055550,2018-02-28 15:30,47400,2018-02-28 15:00,47200,250,47200,47150,837622,...,7535,10,5,2498,17,13,229750.0,1.0,0.0,0.0
4714,대원미디어,048910,2018-02-28 15:30,10300,2018-02-28 15:00,10350,-500,10350,10250,477335,...,3117,2,2,755,3,7,1333.0,0.0,1.0,0.0
4715,BGF,027410,2018-02-28 15:30,12550,2018-02-28 15:00,12550,-150,12600,12550,417142,...,46240,96,48,15444,334,67,4275.0,1.0,0.0,0.0

In [19]:
total_df = total_df.reset_index().drop(["index"], axis = 1)

In [20]:
total_df["yesterday_closing_price"] = total_df["price_1"] - total_df["price_dif_1"]

In [21]:
total_df["is_maximum"] = (((total_df["price_1"] / total_df["yesterday_closing_price"]) - 1) * 100 > 29.5) | \
(((total_df["price_2"] / total_df["yesterday_closing_price"]) - 1) * 100 > 29.5) | \
(((total_df["price_3"] / total_df["yesterday_closing_price"]) - 1) * 100 > 29.5)
total_df["is_maximum"] = total_df["is_maximum"].astype(int)

In [22]:
total_df["is_minimum"] = (((total_df["price_1"] / total_df["yesterday_closing_price"]) - 1) * 100 < -29.5) | \
(((total_df["price_2"] / total_df["yesterday_closing_price"]) - 1) * 100 < -29.5) | \
(((total_df["price_3"] / total_df["yesterday_closing_price"]) - 1) * 100 < -29.5)
total_df["is_minimum"] = total_df["is_maximum"].astype(int)

In [23]:
total_df["price_volatility"] = (((total_df[["price_1", "price_2", "price_3"]].max(axis=1)) / (total_df[["price_1", "price_2", "price_3"]].min(axis=1))) - 1) * 100

In [24]:
total_df["price_trend"] = (((total_df["price_1"] - total_df["price_2"]) < 0).astype(int) + ((total_df["price_2"] - total_df["price_3"]) < 0).astype(int)) - (((total_df["price_1"] - total_df["price_2"]) > 0).astype(int) + ((total_df["price_2"] - total_df["price_3"]) > 0).astype(int))

In [25]:
total_df["average_price_volatility"] = total_df["price_trend"] * total_df["price_volatility"] / 2

In [26]:
total_df["sell_minus_buy_1"] = total_df["sell_1"] - total_df["buy_1"]

In [27]:
total_df["sell_minus_buy_2"] = total_df["sell_2"] - total_df["buy_2"]

In [28]:
total_df["sell_minus_buy_3"] = total_df["sell_3"] - total_df["buy_3"]

In [29]:
total_df["is_price_gap_stable"] = ((total_df["sell_minus_buy_1"] == total_df["sell_minus_buy_2"]) & (total_df["sell_minus_buy_2"] == total_df["sell_minus_buy_3"])).astype(int)

In [30]:
total_df["price_gap_volatility"] = (((total_df[["sell_minus_buy_1", "sell_minus_buy_2", "sell_minus_buy_3"]].max(axis=1)) / (total_df[["sell_minus_buy_1", "sell_minus_buy_2", "sell_minus_buy_3"]].min(axis=1)))) - 1

In [31]:
total_df["is_like_higher"] = (total_df["like_3"] > total_df["dislike_3"]).astype(int)

In [32]:
total_df["volume_trend"] = ((((total_df["volume_3"]) - (total_df["volume_2"] * 1+1e-3)) \
 / ((total_df["volume_2"]) - (total_df["volume_1"] * 1-1e-4))) - 1) * 100

In [33]:
total_df["post_num_trend"] = ((((total_df["post_num_3"]) - (total_df["post_num_2"] * 1+1e-3)) \
 / ((total_df["post_num_2"]) - (total_df["post_num_1"] * 1-1e-4))) - 1) * 100

In [34]:
total_df["unique_id_trend"] = ((((total_df["unique_id_3"]) - (total_df["unique_id_2"] * 1+1e-3)) \
 / ((total_df["unique_id_2"]) - (total_df["unique_id_1"] * 1-1e-4))) - 1) * 100

In [35]:
total_df["click_trend"] = ((((total_df["click_3"]) - (total_df["click_2"] * 1+1e-3)) \
 / ((total_df["click_2"]) - (total_df["click_1"] * 1-1e-4))) - 1) * 100

In [36]:
total_df["price_increase"] = ((total_df["price"] / total_df["price_3"]) - 1) * 100

In [37]:
total_df["did_price_increase"] = (total_df["price_increase"] > 0).astype(int)

In [38]:
total_df["did_price_033"] = (total_df["price_increase"] > 0.33).astype(int)

In [39]:
total_df["did_price_100"] = (total_df["price_increase"] > 1.0).astype(int)

In [40]:
total_df["did_price_150"] = (total_df["price_increase"] > 1.5).astype(int)

In [41]:
#total_df.to_json('ten_min_low_freq_transaction_cost.json', orient='values')

In [42]:
with open('KOSPI_Feb21_Feb28.json', 'r', encoding='UTF-8') as f:
    kospi = json.load(f)

In [43]:
with open('KOSDAQ_Feb21_Feb28.json', 'r', encoding='UTF-8') as f:
    kosdaq = json.load(f)

In [44]:
total_df["kospi_ind"] = np.nan
total_df["kosdaq_ind"] = np.nan
total_df["time_slot"] = np.nan
total_df["ko_inter"] = np.nan
total_df["early_mor"] = np.nan
total_df["morning"] = np.nan
total_df["lunch"] = np.nan
total_df["afternoon"] = np.nan
total_df["late"] = np.nan
total_df["mkt_change"] = np.nan
num = 1
time_list = []
for index, row in total_df.iterrows():
    pi_ind = kospi[row['time']]
    daq_ind = kosdaq[row['time']]
    total_df.set_value(index,'kospi_ind', pi_ind)
    total_df.set_value(index,'kosdaq_ind', daq_ind)
    time = row['time'].split()[1]
    if time not in time_list:
        time_list.append(time)
    ind = time_list.index(time)
    num = index + 1
    
    if num in [1, 2, 3]:
        early_mor = 1
    else:
        early_mor = 0
    
    if (num >= 1) and (num <= 15):
        morning = 1
    else:
        morning = 0
        
    if (num >= 16) and (num <= 24):
        lunch = 1
    else:
        lunch = 0
    
    if (num >= 25) and (num <= 36):
        afternoon = 1
    else:
        afternoon = 0
    
    if (num >= 25) and (num <= 36):
        afternoon = 1
    else:
        afternoon = 0
    
    if (num >= 31) and (num <= 36):
        late = 1
    else:
        late = 0
        
    mkt_change = row['kospi'] * pi_ind + row['kosdaq'] * daq_ind
    total_df.set_value(index,'mkt_change', mkt_change)
    total_df.set_value(index,'early_mor', early_mor)
    total_df.set_value(index,'morning', morning)
    total_df.set_value(index,'lunch', lunch)
    total_df.set_value(index,'afternoon', afternoon)
    total_df.set_value(index,'late', late)
    total_df.set_value(index,'time_slot', num)
    total_df.set_value(index,'ko_inter', pi_ind * daq_ind)

In [45]:
#total_df.to_json('data_to_analyze.json', orient='values')

In [46]:
#lets do analysis on two files one with square term the other without

In [47]:
total_df.columns

Index(['name', 'code', 'time', 'price', 'time_1', 'price_1', 'price_dif_1',
       'sell_1', 'buy_1', 'volume_1', 'variation_1', 'post_num_1',
       'unique_id_1', 'click_1', 'like_1', 'dislike_1', 'time_2', 'price_2',
       'price_dif_2', 'sell_2', 'buy_2', 'volume_2', 'variation_2',
       'post_num_2', 'unique_id_2', 'click_2', 'like_2', 'dislike_2', 'time_3',
       'price_3', 'price_dif_3', 'sell_3', 'buy_3', 'volume_3', 'variation_3',
       'post_num_3', 'unique_id_3', 'click_3', 'like_3', 'dislike_3',
       'mkt_cap', 'kospi', 'kosdaq', 'trash', 'yesterday_closing_price',
       'is_maximum', 'is_minimum', 'price_volatility', 'price_trend',
       'average_price_volatility', 'sell_minus_buy_1', 'sell_minus_buy_2',
       'sell_minus_buy_3', 'is_price_gap_stable', 'price_gap_volatility',
       'is_like_higher', 'volume_trend', 'post_num_trend', 'unique_id_trend',
       'click_trend', 'price_increase', 'did_price_increase', 'did_price_033',
       'did_price_100', 'did_price_150', 'kospi_ind', 'kosdaq_ind',
       'time_slot', 'ko_inter', 'early_mor', 'morning', 'lunch', 'afternoon',
       'late', 'mkt_change'],
      dtype='object')

In [48]:
CONT_COLUMNS = ['price', 'price_1', 'price_dif_1', 'sell_1', 'buy_1', 'volume_1', 'variation_1', 
                'post_num_1', 'unique_id_1', 'click_1', 'like_1', 'dislike_1', 'price_2', 
                'price_dif_2', 'sell_2', 'buy_2', 'volume_2', 'variation_2', 'post_num_2', 
                'unique_id_2', 'click_2', 'like_2', 'dislike_2', 'price_3', 'price_dif_3', 
                'sell_3', 'buy_3', 'volume_3', 'variation_3', 'post_num_3', 'unique_id_3', 
                'click_3', 'like_3', 'dislike_3', 'mkt_cap', 'kospi', 'kosdaq', 'trash', 
                'yesterday_closing_price', 'is_maximum', 'is_minimum', 'price_volatility', 
                'price_trend', 'average_price_volatility', 'sell_minus_buy_1', 'sell_minus_buy_2',
                'sell_minus_buy_3', 'is_price_gap_stable', 'price_gap_volatility', 'is_like_higher', 
                'volume_trend', 'post_num_trend', 'unique_id_trend', 'click_trend', 'price_increase', 
                'did_price_increase', 'did_price_033', 'did_price_100', 'did_price_150', 
                'kospi_ind', 'kosdaq_ind', 'time_slot', 'early_mor', 'morning', 'lunch', 'afternoon', 'late', 
                'mkt_change']

In [49]:
for var in CONT_COLUMNS:
    col_name = var + '_sq'
    total_df[col_name] = np.nan
    for index, row in total_df.iterrows():
        sqr = row[var] ** 2
        total_df.set_value(index, col_name, sqr)

In [50]:
total_df

,name,code,time,price,time_1,price_1,price_dif_1,sell_1,buy_1,volume_1,...,did_price_150_sq,kospi_ind_sq,kosdaq_ind_sq,time_slot_sq,early_mor_sq,morning_sq,lunch_sq,afternoon_sq,late_sq,mkt_change_sq
0,크리스탈,083790,2018-02-21 09:40,27500,2018-02-21 09:10,26800,-100,26850,26800,18097,...,0.0,0.049072,1.509418,1.0,1.0,1.0,0.0,0.0,0.0,1.509418
1,LG유플러스,032640,2018-02-21 09:40,12900,2018-02-21 09:10,13000,0,13000,12950,146579,...,0.0,0.049072,1.509418,4.0,1.0,1.0,0.0,0.0,0.0,0.049072
2,마크로젠,038290,2018-02-21 09:40,48300,2018-02-21 09:10,47100,0,47100,47050,10608,...,0.0,0.049072,1.509418,9.0,1.0,1.0,0.0,0.0,0.0,1.509418
3,LS산전,010120,2018-02-21 09:40,58200,2018-02-21 09:10,57800,200,57800,57600,2835,...,0.0,0.049072,1.509418,16.0,0.0,1.0,0.0,0.0,0.0,0.049072
4,CJ,001040,2018-02-21 09:40,163000,2018-02-21 09:10,161500,-1000,162000,161500,2440,...,0.0,0.049072,1.509418,25.0,0.0,1.0,0.0,0.0,0.0,0.049072
5,홈캐스트,064240,2018-02-21 09:40,12900,2018-02-21 09:10,12700,50,12700,12650,23346,...,0.0,0.049072,1.509418,36.0,0.0,1.0,0.0,0.0,0.0,1.509418
6,한국콜마홀딩스,024720,2018-02-21 09:40,47500,2018-02-21 09:10,50200,4100,50300,50200,176091,...,0.0,0.049072,1.509418,49.0,0.0,1.0,0.0,0.0,0.0,0.049072
7,에이프로젠제약,003060,2018-02-21 09:40,4500,2018-02-21 09:10,4465,15,4470,4465,51527,...,0.0,0.049072,1.509418,64.0,0.0,1.0,0.0,0.0,0.0,0.049072
8,대한항공,003490,2018-02-21 09:40,35700,2018-02-21 09:10,35300,-100,35300,35250,10548,...,0.0,0.049072,1.509418,81.0,0.0,1.0,0.0,0.0,0.0,0.049072
9,KD건설,044180,2018-02-21 09:40,171,2018-02-21 09:10,172,-1,172,171,3173638,...,0.0,0.049072,1.509418,100.0,0.0,1.0,0.0,0.0,0.0,1.509418
10,유니온머티리얼,047400,2018-02-21 09:40,2735,2018-02-21 09:10,2685,25,2685,2655,4877,...,0.0,0.049072,1.509418,121.0,0.0,1.0,0.0,0.0,0.0,0.049072
11,동양생명,082640,2018-02-21 09:40,7540,2018-02-21 09:10,7500,-60,7500,7490,7763,...,0.0,0.049072,1.509418,144.0,0.0,1.0,0.0,0.0,0.0,0.049072
12,삼성에스디에스,018260,2018-02-21 09:40,238000,2018-02-21 09:10,235000,500,235000,234500,4211,...,0.0,0.049072,1.509418,169.0,0.0,1.0,0.0,0.0,0.0,0.049072
13,BGF,027410,2018-02-21 09:40,13700,2018-02-21 09:10,13500,50,13550,13500,10787,...,0.0,0.049072,1.509418,196.0,0.0,1.0,0.0,0.0,0.0,0.049072
14,효성,004800,2018-02-21 09:40,124500,2018-02-21 09:10,123500,500,123500,123000,1809,...,0.0,0.049072,1.509418,225.0,0.0,1.0,0.0,0.0,0.0,0.049072
15,큐렉소,060280,2018-02-21 09:40,8740,2018-02-21 09:10,8620,0,8610,8590,8831,...,0.0,0.049072,1.509418,256.0,0.0,0.0,1.0,0.0,0.0,1.509418
16,유니슨,018000,2018-02-21 09:40,3555,2018-02-21 09:10,3465,-35,3465,3460,38785,...,1.0,0.049072,1.509418,289.0,0.0,0.0,1.0,0.0,0.0,1.509418
17,아모레퍼시픽,090430,2018-02-21 09:40,283500,2018-02-21 09:10,281000,5500,281500,281000,16268,...,0.0,0.049072,1.509418,324.0,0.0,0.0,1.0,0.0,0.0,0.049072
18,만도,204320,2018-02-21 09:40,240000,2018-02-21 09:10,239500,5000,239500,239000,2817,...,0.0,0.049072,1.509418,361.0,0.0,0.0,1.0,0.0,0.0,0.049072
19,아이진,185490,2018-02-21 09:40,21600,2018-02-21 09:10,21700,0,21750,21650,7185,...,0.0,0.049072,1.509418,400.0,0.0,0.0,1.0,0.0,0.0,1.509418
20,휠라코리아,081660,2018-02-21 09:40,87900,2018-02-21 09:10,88000,500,88000,87800,43,...,0.0,0.049072,1.509418,441.0,0.0,0.0,1.0,0.0,0.0,0.049072
21,용평리조트,070960,2018-02-21 09:40,8510,2018-02-21 09:10,8460,-30,8490,8460,28183,...,0.0,0.049072,1.509418,484.0,0.0,0.0,1.0,0.0,0.0,0.049072
22,바이오스마트,038460,2018-02-21 09:40,6420,2018-02-21 09:10,6370,10,6370,6360,38142,...,0.0,0.049072,1.509418,529.0,0.0,0.0,1.0,0.0,0.0,1.509418
23,LG이노텍,011070,2018-02-21 09:40,126500,2018-02-21 09:10,126000,500,126000,125500,19201,...,0.0,0.049072,1.509418,576.0,0.0,0.0,1.0,0.0,0.0,0.049072
24,캠시스,050110,2018-02-21 09:40,2990,2018-02-21 09:10,3005,55,3010,3005,1206468,...,0.0,0.049072,1.509418,625.0,0.0,0.0,0.0,1.0,0.0,1.509418
25,키움증권,039490,2018-02-21 09:40,105500,2018-02-21 09:10,104000,-500,104000,103500,2597,...,0.0,0.049072,1.509418,676.0,0.0,0.0,0.0,1.0,0.0,0.049072
26,SK케미칼,285130,2018-02-21 09:40,110500,2018-02-21 09:10,109000,-500,110000,109500,2172,...,0.0,0.049072,1.509418,729.0,0.0,0.0,0.0,1.0,0.0,0.049072
27,액션스퀘어,205500,2018-02-21 09:40,8460,2018-02-21 09:10,8480,10,8500,8480,36783,...,1.0,0.049072,1.509418,784.0,0.0,0.0,0.0,1.0,0.0,1.509418
28,SKC코오롱PI,178920,2018-02-21 09:40,41250,2018-02-21 09:10,40950,800,40950,40900,27890,...,1.0,0.049072,1.509418,841.0,0.0,0.0,0.0,1.0,0.0,1.509418
29,톱텍,108230,2018-02-21 09:40,29850,2018-02-21 09:10,29000,-100,29150,29050,17478,...,1.0,0.049072,1.509418,900.0,0.0,0.0,0.0,1.0,0.0,1.509418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24919,삼진엘앤디,054090,2018-02-28 15:30,2470,2018-02-28 15:00,2490,-20,2490,2465,87759,...,0.0,1.377790,3.756592,621006400.0,0.0,0.0,0.0,0.0,0.0,3.756592
24920,한전KPS,051600,2018-02-28 15:30,40350,2018-02-28 15:00,40450,-200,40500,40450,62721,...,0.0,1.377790,3.756592,621056241.0,0.0,0.0,0.0,0.0,0.0,1.377790
24921,조아제약,034940,2018-02-28 15:30,5580,2018-02-28 15:00,5600,-250,5610,5600,673986,...,0.0,1.377790,3.756592,621106084.0,0.0,0.0,0.0,0.0,0.0,3.756592
24922,대주전자재료,078600,2018-02-28 15:30,14900,2018-02-28 15:00,14900,-1150,14900,14850,295112,...,0.0,1.377790,3.756592,621155929.0,0.0,0.0,0.0,0.0,0.0,3.756592
24923,디스플레이텍,066670,2018-02-28 15:30,3790,2018-02-28 15:00,3760,-45,3760,3735,18341,...,0.0,1.377790,3.756592,621205776.0,0.0,0.0,0.0,0.0,0.0,3.756592
24924,지어소프트,051160,2018-02-28 15:30,2060,2018-02-28 15:00,2065,20,2065,2055,109990,...,0.0,1.377790,3.756592,621255625.0,0.0,0.0,0.0,0.0,0.0,3.756592
24925,아세아제지,002310,2018-02-28 15:30,24150,2018-02-28 15:00,24150,850,24150,24050,53783,...,0.0,1.377790,3.756592,621305476.0,0.0,0.0,0.0,0.0,0.0,1.377790
24926,세아베스틸,001430,2018-02-28 15:30,28500,2018-02-28 15:00,28450,450,28500,28450,61598,...,0.0,1.377790,3.756592,621355329.0,0.0,0.0,0.0,0.0,0.0,1.377790
24927,코라오홀딩스,900140,2018-02-28 15:30,4680,2018-02-28 15:00,4685,-15,4685,4680,111182,...,0.0,1.377790,3.756592,621405184.0,0.0,0.0,0.0,0.0,0.0,1.377790
24928,에스앤씨엔진그룹,900080,2018-02-28 15:30,959,2018-02-28 15:00,960,-8,960,959,286613,...,0.0,1.377790,3.756592,621455041.0,0.0,0.0,0.0,0.0,0.0,3.756592
24929,코스맥스비티아이,044820,2018-02-28 15:30,33350,2018-02-28 15:00,33200,-400,33200,33150,9499,...,0.0,1.377790,3.756592,621504900.0,0.0,0.0,0.0,0.0,0.0,1.377790
24930,삼지전자,037460,2018-02-28 15:30,12500,2018-02-28 15:00,12400,-100,12400,12350,187338,...,0.0,1.377790,3.756592,621554761.0,0.0,0.0,0.0,0.0,0.0,3.756592
24931,강스템바이오텍,217730,2018-02-28 15:30,12500,2018-02-28 15:00,12250,-600,12250,12200,166081,...,0.0,1.377790,3.756592,621604624.0,0.0,0.0,0.0,0.0,0.0,3.756592
24932,애경유화,161000,2018-02-28 15:30,18200,2018-02-28 15:00,18300,350,18300,18250,91416,...,0.0,1.377790,3.756592,621654489.0,0.0,0.0,0.0,0.0,0.0,1.377790
24933,한전산업,130660,2018-02-28 15:30,4005,2018-02-28 15:00,4015,-10,4020,4015,17143,...,0.0,1.377790,3.756592,621704356.0,0.0,0.0,0.0,0.0,0.0,1.377790
24934,쎄트렉아이,099320,2018-02-28 15:30,40900,2018-02-28 15:00,40650,250,40700,40650,27010,...,0.0,1.377790,3.756592,621754225.0,0.0,0.0,0.0,0.0,0.0,3.756592
24935,파트론,091700,2018-02-28 15:30,9330,2018-02-28 15:00,9150,-460,9170,9150,976067,...,0.0,1.377790,3.756592,621804096.0,0.0,0.0,0.0,0.0,0.0,3.756592
24936,흥구석유,024060,2018-02-28 15:30,2730,2018-02-28 15:00,2745,-30,2745,2740,1936,...,0.0,1.377790,3.756592,621853969.0,0.0,0.0,0.0,0.0,0.0,3.756592
24937,코오롱인더,120110,2018-02-28 15:30,71100,2018-02-28 15:00,71400,-1800,71400,71300,199868,...,0.0,1.377790,3.756592,621903844.0,0.0,0.0,0.0,0.0,0.0,1.377790
24938,지스마트글로벌,114570,2018-02-28 15:30,13350,2018-02-28 15:00,13350,-450,13400,13350,246022,...,0.0,1.377790,3.756592,621953721.0,0.0,0.0,0.0,0.0,0.0,3.756592
24939,코미팜,041960,2018-02-28 15:30,39000,2018-02-28 15:00,39000,-800,39050,39000,156118,...,0.0,1.377790,3.756592,622003600.0,0.0,0.0,0.0,0.0,0.0,3.756592
24940,대창스틸,140520,2018-02-28 15:30,4165,2018-02-28 15:00,4210,-100,4210,4200,162049,...,0.0,1.377790,3.756592,622053481.0,0.0,0.0,0.0,0.0,0.0,3.756592
24941,골프존뉴딘,121440,2018-02-28 15:30,6040,2018-02-28 15:00,6090,-110,6100,6090,238004,...,0.0,1.377790,3.756592,622103364.0,0.0,0.0,0.0,0.0,0.0,3.756592
24942,테스,095610,2018-02-28 15:30,33450,2018-02-28 15:00,33050,-800,33100,33050,103955,...,0.0,1.377790,3.756592,622153249.0,0.0,0.0,0.0,0.0,0.0,3.756592
24943,루트로닉,085370,2018-02-28 15:30,13150,2018-02-28 15:00,13200,-700,13300,13200,235748,...,0.0,1.377790,3.756592,622203136.0,0.0,0.0,0.0,0.0,0.0,3.756592
24944,이라이콤,041520,2018-02-28 15:30,6860,2018-02-28 15:00,6910,-50,6910,6900,14009,...,0.0,1.377790,3.756592,622253025.0,0.0,0.0,0.0,0.0,0.0,3.756592
24945,EG,037370,2018-02-28 15:30,10150,2018-02-28 15:00,10250,-700,10300,10250,87397,...,0.0,1.377790,3.756592,622302916.0,0.0,0.0,0.0,0.0,0.0,3.756592
24946,신한지주,055550,2018-02-28 15:30,47400,2018-02-28 15:00,47200,250,47200,47150,837622,...,0.0,1.377790,3.756592,622352809.0,0.0,0.0,0.0,0.0,0.0,1.377790
24947,대원미디어,048910,2018-02-28 15:30,10300,2018-02-28 15:00,10350,-500,10350,10250,477335,...,0.0,1.377790,3.756592,622402704.0,0.0,0.0,0.0,0.0,0.0,3.756592
24948,BGF,027410,2018-02-28 15:30,12550,2018-02-28 15:00,12550,-150,12600,12550,417142,...,0.0,1.377790,3.756592,622452601.0,0.0,0.0,0.0,0.0,0.0,1.377790

In [59]:
#total_df.to_json('data_to_analyze_ki.json', orient='values')