In [1]:
import json
import pandas as pd
import numpy as np

In [2]:
with open("df_1hour_Feb.json", 'r', encoding='UTF-8') as f:
    F_data = json.load(f)

In [3]:
with open("df_1hour_Mar_05.json", 'r', encoding='UTF-8') as f:
    M_data = json.load(f)

In [4]:
COLUMNS = ['name', 'code', 'time', 'price', 'time_1', 'price_1', 'price_dif_1', 'sell_1', 'buy_1', 'volume_1', 'variation_1', 'post_num_1', 'unique_id_1', 'click_1', 'like_1', 'dislike_1', 'time_2', 'price_2', 'price_dif_2', 'sell_2', 'buy_2', 'volume_2', 'variation_2', 'post_num_2', 'unique_id_2', 'click_2', 'like_2', 'dislike_2', 'time_3', 'price_3', 'price_dif_3', 'sell_3', 'buy_3', 'volume_3', 'variation_3', 'post_num_3', 'unique_id_3', 'click_3', 'like_3', 'dislike_3', 'mkt_cap', 'kospi', 'kosdaq', 'trash', 'yesterday_closing_price', 'is_maximum', 'is_minimum', 'price_volatility', 'price_trend', 'average_price_volatility', 'sell_minus_buy_1', 'sell_minus_buy_2', 'sell_minus_buy_3', 'is_price_gap_stable', 'price_gap_volatility', 'is_like_higher', 'volume_trend', 'post_num_trend', 'unique_id_trend', 'click_trend', 'price_increase', 'did_price_increase', 'did_price_033', 'did_price_100', 'did_price_150', 'kospi_ind', 'kosdaq_ind', 'time_slot', 'ko_inter', 'early_mor', 'morning', 'lunch', 'afternoon', 'late', 'mkt_change', 'alpha', 'per_now', 'kospi_1', 'kospi_2', 'kospi_3', 'kospi_answer', 'kosdaq_1', 'kosdaq_2', 'kosdaq_3', 'kosdaq_answer', 'kospi_trend', 'kosdaq_trend', 'kospi_increase', 'kosdaq_increase', 'market_increase', 'did_opening_price_increase', 'price_1_sq', 'price_dif_1_sq', 'sell_1_sq', 'buy_1_sq', 'volume_1_sq', 'variation_1_sq', 'post_num_1_sq', 'unique_id_1_sq', 'click_1_sq', 'like_1_sq', 'dislike_1_sq', 'price_2_sq', 'price_dif_2_sq', 'sell_2_sq', 'buy_2_sq', 'volume_2_sq', 'variation_2_sq', 'post_num_2_sq', 'unique_id_2_sq', 'click_2_sq', 'like_2_sq', 'dislike_2_sq', 'price_3_sq', 'price_dif_3_sq', 'sell_3_sq', 'buy_3_sq', 'volume_3_sq', 'variation_3_sq', 'post_num_3_sq', 'unique_id_3_sq', 'click_3_sq', 'like_3_sq', 'dislike_3_sq', 'mkt_cap_sq', 'yesterday_closing_price_sq', 'price_volatility_sq', 'price_trend_sq', 'average_price_volatility_sq', 'sell_minus_buy_1_sq', 'sell_minus_buy_2_sq', 'sell_minus_buy_3_sq', 'price_gap_volatility_sq', 'volume_trend_sq', 'post_num_trend_sq', 'unique_id_trend_sq', 'click_trend_sq', 'kospi_ind_sq', 'kosdaq_ind_sq', 'time_slot_sq', 'ko_inter_sq', 'mkt_change_sq', 'alpha_sq', 'per_now_sq', 'kospi_1_sq', 'kospi_2_sq', 'kospi_3_sq', 'kosdaq_1_sq', 'kosdaq_2_sq', 'kosdaq_3_sq', 'kospi_trend_sq', 'kosdaq_trend_sq']

In [5]:
df_F = pd.DataFrame(F_data, columns = COLUMNS)
df_M = pd.DataFrame(M_data, columns = COLUMNS)
df = pd.concat([df_F, df_M])

In [6]:
df = df.dropna(axis=0, how='any')

In [7]:
with open("KNN_mod.json", 'r', encoding='UTF-8') as f:
    KNN = json.load(f)

In [8]:
with open("Logistic_mod.json", 'r', encoding='UTF-8') as f:
    Logistic = json.load(f)

In [9]:
with open("PLS_mod.json", 'r', encoding='UTF-8') as f:
    PLS = json.load(f)

In [10]:
with open("RF_mod.json", 'r', encoding='UTF-8') as f:
    RF = json.load(f)

In [11]:
with open("BAGGING_mod.json", 'r', encoding='UTF-8') as f:
    BAG = json.load(f)

In [12]:
with open("Boosting_mod.json", 'r', encoding='UTF-8') as f:
    BOOST = json.load(f)

In [13]:
with open("PCR_mod.json", 'r', encoding='UTF-8') as f:
    PCR = json.load(f)

In [14]:
KNN_mod = pd.DataFrame(np.nan, index=range(df.shape[0]), columns=['KNN'])
KNN_val = pd.DataFrame(KNN, index = range(11629, df.shape[0]), columns=['KNN'])
KNN_mod.update(KNN_val)

In [15]:
PLS_mod = pd.DataFrame(np.nan, index=range(df.shape[0]), columns=['PLS'])
PLS_val = pd.DataFrame(PLS, index = range(11629, df.shape[0]), columns=['PLS'])
PLS_mod.update(PLS_val)

In [16]:
LOG_mod = pd.DataFrame(np.nan, index=range(df.shape[0]), columns=['Logistic'])
LOG_val = pd.DataFrame(Logistic, index = range(11629, df.shape[0]), columns=['Logistic'])
LOG_mod.update(LOG_val)

In [17]:
RF_mod = pd.DataFrame(np.nan, index=range(df.shape[0]), columns=['Random Forest'])
RF_val = pd.DataFrame(RF, index = range(11629, df.shape[0]), columns=['Random Forest'])
RF_mod.update(RF_val)

In [18]:
BAG_mod = pd.DataFrame(np.nan, index=range(df.shape[0]), columns=['Bagging'])
BAG_val = pd.DataFrame(BAG, index = range(11629, df.shape[0]), columns=['Bagging'])
BAG_mod.update(BAG_val)

In [19]:
BOOST_mod = pd.DataFrame(np.nan, index=range(df.shape[0]), columns=['Boosting'])
BOOST_val = pd.DataFrame(BOOST, index = range(11629, df.shape[0]), columns=['Boosting'])
BOOST_mod.update(BOOST_val)

In [20]:
PCR_mod = pd.DataFrame(np.nan, index=range(df.shape[0]), columns=['PCR'])
PCR_val = pd.DataFrame(PCR, index = range(11629, df.shape[0]), columns=['PCR'])
PCR_mod.update(PCR_val)

In [21]:
df = df.reset_index()

In [22]:
df = pd.concat([df, KNN_mod, PLS_mod, LOG_mod, RF_mod, BAG_mod, BOOST_mod, PCR_mod], axis = 1)

In [23]:
df

,index,name,code,time,price,time_1,price_1,price_dif_1,sell_1,buy_1,...,kosdaq_3_sq,kospi_trend_sq,kosdaq_trend_sq,KNN,PLS,Logistic,Random Forest,Bagging,Boosting,PCR
0,0,호텔신라,008770,2018-02-14 10:30,83400,2018-02-14 09:10,84700,1800,84800,84700,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,대한광통신,010170,2018-02-14 10:30,7030,2018-02-14 09:10,7060,90,7060,7050,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,포스코 ICT,022100,2018-02-14 10:30,8290,2018-02-14 09:10,8310,0,8330,8310,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,한화케미칼,009830,2018-02-14 10:30,32450,2018-02-14 09:10,32700,550,32700,32650,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,지엘팜텍,204840,2018-02-14 10:30,4780,2018-02-14 09:10,4680,50,4700,4680,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,코웰패션,033290,2018-02-14 10:30,5340,2018-02-14 09:10,5270,90,5280,5270,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,대한항공,003490,2018-02-14 10:30,35550,2018-02-14 09:10,35700,300,35750,35700,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,대한뉴팜,054670,2018-02-14 10:30,13700,2018-02-14 09:10,13800,0,13800,13750,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,레드캡투어,038390,2018-02-14 10:30,15300,2018-02-14 09:10,15350,100,15350,15200,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,이마트,139480,2018-02-14 10:30,289000,2018-02-14 09:10,283500,5000,284000,283500,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,녹십자,006280,2018-02-14 10:30,206000,2018-02-14 09:10,201000,1500,201000,200000,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,GS,078930,2018-02-14 10:30,63300,2018-02-14 09:10,62600,100,62700,62600,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,CJ헬로,037560,2018-02-14 10:30,8880,2018-02-14 09:10,8650,230,8650,8640,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,모토닉,009680,2018-02-14 10:30,10100,2018-02-14 09:10,10300,50,10300,10200,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,AJ렌터카,068400,2018-02-14 10:30,10450,2018-02-14 09:10,10400,0,10550,10400,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,한국전자홀딩스,006200,2018-02-14 10:30,793,2018-02-14 09:10,795,-3,795,793,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16,일진머티리얼즈,020150,2018-02-14 10:30,32250,2018-02-14 09:10,32300,350,32250,32200,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17,코위버,056360,2018-02-14 10:30,7780,2018-02-14 09:10,7870,120,7890,7870,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18,앱클론,174900,2018-02-14 10:30,55200,2018-02-14 09:10,54300,0,54300,54200,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19,디에이치피코리아,131030,2018-02-14 10:30,10500,2018-02-14 09:10,10400,350,10450,10400,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20,지스마트글로벌,114570,2018-02-14 10:30,13750,2018-02-14 09:10,13850,650,13900,13850,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,21,씨케이에이치,900120,2018-02-14 10:30,836,2018-02-14 09:10,846,1,852,846,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,삼우엠스,082660,2018-02-14 10:30,823,2018-02-14 09:10,828,12,828,816,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23,인트론바이오,048530,2018-02-14 10:30,38550,2018-02-14 09:10,37650,-100,37650,37600,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,24,휴온스,243070,2018-02-14 10:30,96100,2018-02-14 09:10,94000,1900,94100,94000,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,25,알서포트,131370,2018-02-14 10:30,2730,2018-02-14 09:10,2730,35,2735,2730,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,26,에스에너지,095910,2018-02-14 10:30,6670,2018-02-14 09:10,6710,50,6710,6660,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,키움증권,039490,2018-02-14 10:30,106500,2018-02-14 09:10,106000,500,106000,105500,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,28,녹십자셀,031390,2018-02-14 10:30,50500,2018-02-14 09:10,49750,-250,49800,49750,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,성광벤드,014620,2018-02-14 10:30,12000,2018-02-14 09:10,12200,150,12250,12200,...,694172.248894,3854.752292,19942.338412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15635,2221,덕우전자,263600,2018-03-05 15:30,14150,2018-03-05 14:10,14400,-550,14400,14350,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,1.0,1.0,0.0,1.0
15636,2222,코프라,126600,2018-03-05 15:30,4545,2018-03-05 14:10,4480,-110,4485,4480,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15637,2223,에스텍,069510,2018-03-05 15:30,10700,2018-03-05 14:10,10600,-150,10650,10600,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15638,2224,키이스트,054780,2018-03-05 15:30,2295,2018-03-05 14:10,2295,-5,2300,2295,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15639,2225,황금에스티,032560,2018-03-05 15:30,10900,2018-03-05 14:10,11150,-150,11150,11100,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,1.0,1.0,0.0,0.0
15640,2226,디에스티로봇,090710,2018-03-05 15:30,2375,2018-03-05 14:10,2375,-30,2380,2375,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,1.0,0.0,0.0,0.0
15641,2227,하나금융지주,086790,2018-03-05 15:30,48050,2018-03-05 14:10,48200,-600,48200,48150,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15642,2228,세코닉스,053450,2018-03-05 15:30,12850,2018-03-05 14:10,12950,-350,12950,12900,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,1.0,0.0,0.0,0.0
15643,2229,텔코웨어,078000,2018-03-05 15:30,14400,2018-03-05 14:10,14400,400,14450,14400,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15644,2230,유아이엘,049520,2018-03-05 15:30,6790,2018-03-05 14:10,6820,-40,6820,6810,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15645,2231,NICE,034310,2018-03-05 15:30,16000,2018-03-05 14:10,15900,-150,15900,15850,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15646,2232,연이정보통신,090740,2018-03-05 15:30,2480,2018-03-05 14:10,2465,-80,2485,2465,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15647,2233,화진,134780,2018-03-05 15:30,4900,2018-03-05 14:10,4965,-65,4965,4960,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15648,2234,국순당,043650,2018-03-05 15:30,5730,2018-03-05 14:10,5760,-40,5760,5750,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15649,2235,디지털대성,068930,2018-03-05 15:30,4135,2018-03-05 14:10,4135,55,4135,4130,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15650,2236,인천도시가스,034590,2018-03-05 15:30,30000,2018-03-05 14:10,30000,150,30100,30000,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15651,2237,JW생명과학,234080,2018-03-05 15:30,50900,2018-03-05 14:10,51700,-1200,51700,51600,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15652,2238,애경유화,161000,2018-03-05 15:30,17750,2018-03-05 14:10,17800,-200,17850,17800,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15653,2239,푸른저축은행,007330,2018-03-05 15:30,7700,2018-03-05 14:10,7710,-70,7710,7700,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15654,2240,효성,004800,2018-03-05 15:30,120000,2018-03-05 14:10,121500,500,121500,121000,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15655,2241,오이솔루션,138080,2018-03-05 15:30,10800,2018-03-05 14:10,10850,-100,10900,10850,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15656,2242,국도화학,007690,2018-03-05 15:30,60500,2018-03-05 14:10,60700,-1500,60700,60600,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,1.0,0.0
15657,2243,제룡전기,033100,2018-03-05 15:30,6940,2018-03-05 14:10,7010,310,7010,7000,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15658,2244,한솔제지,213500,2018-03-05 15:30,16000,2018-03-05 14:10,16100,-250,16100,16050,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15659,2245,서진오토모티브,122690,2018-03-05 15:30,3945,2018-03-05 14:10,3960,-15,3960,3950,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15660,2246,이화전기,024810,2018-03-05 15:30,377,2018-03-05 14:10,375,22,375,374,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15661,2247,국일제지,078130,2018-03-05 15:30,883,2018-03-05 14:10,898,-6,898,897,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15662,2248,퓨쳐켐,220100,2018-03-05 15:30,18350,2018-03-05 14:10,18500,-900,18500,18450,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,1.0,0.0,0.0,0.0
15663,2249,미래에셋생명,085620,2018-03-05 15:30,5140,2018-03-05 14:10,5100,-100,5110,5100,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15664,2250,티비씨,033830,2018-03-05 15:30,694,2018-03-05 14:10,701,1,701,695,...,721310.490000,31042.434395,21506.570857,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
for i in df.columns:
    print(i)

index
name
code
time
price
time_1
price_1
price_dif_1
sell_1
buy_1
volume_1
variation_1
post_num_1
unique_id_1
click_1
like_1
dislike_1
time_2
price_2
price_dif_2
sell_2
buy_2
volume_2
variation_2
post_num_2
unique_id_2
click_2
like_2
dislike_2
time_3
price_3
price_dif_3
sell_3
buy_3
volume_3
variation_3
post_num_3
unique_id_3
click_3
like_3
dislike_3
mkt_cap
kospi
kosdaq
trash
yesterday_closing_price
is_maximum
is_minimum
price_volatility
price_trend
average_price_volatility
sell_minus_buy_1
sell_minus_buy_2
sell_minus_buy_3
is_price_gap_stable
price_gap_volatility
is_like_higher
volume_trend
post_num_trend
unique_id_trend
click_trend
price_increase
did_price_increase
did_price_033
did_price_100
did_price_150
kospi_ind
kosdaq_ind
time_slot
ko_inter
early_mor
morning
lunch
afternoon
late
mkt_change
alpha
per_now
kospi_1
kospi_2
kospi_3
kospi_answer
kosdaq_1
kosdaq_2
kosdaq_3
kosdaq_answer
kospi_trend
kosdaq_trend
kospi_increase
kosdaq_increase
market_increase
did_opening_price_increase
price_1_sq
price_dif_1_sq
sell_1_sq
buy_1_sq
volume_1_sq
variation_1_sq
post_num_1_sq
unique_id_1_sq
click_1_sq
like_1_sq
dislike_1_sq
price_2_sq
price_dif_2_sq
sell_2_sq
buy_2_sq
volume_2_sq
variation_2_sq
post_num_2_sq
unique_id_2_sq
click_2_sq
like_2_sq
dislike_2_sq
price_3_sq
price_dif_3_sq
sell_3_sq
buy_3_sq
volume_3_sq
variation_3_sq
post_num_3_sq
unique_id_3_sq
click_3_sq
like_3_sq
dislike_3_sq
mkt_cap_sq
yesterday_closing_price_sq
price_volatility_sq
price_trend_sq
average_price_volatility_sq
sell_minus_buy_1_sq
sell_minus_buy_2_sq
sell_minus_buy_3_sq
price_gap_volatility_sq
volume_trend_sq
post_num_trend_sq
unique_id_trend_sq
click_trend_sq
kospi_ind_sq
kosdaq_ind_sq
time_slot_sq
ko_inter_sq
mkt_change_sq
alpha_sq
per_now_sq
kospi_1_sq
kospi_2_sq
kospi_3_sq
kosdaq_1_sq
kosdaq_2_sq
kosdaq_3_sq
kospi_trend_sq
kosdaq_trend_sq
KNN
PLS
Logistic
Random Forest
Bagging
Boosting
PCR

In [24]:
df.to_json('model_df_weiwei_0305.json', orient='values')

In [57]:
'''
df['KNN_ans'] = 1 + (df['KNN'] * df['price_increase']) - 0.0033
'''

In [58]:
'''
gb = pd.DataFrame(df.groupby('time')['KNN_ans'].mean()).reset_index()
'''

In [59]:
'''
gb['KNN_balance'] = np.nan
'''

In [60]:
'''
for idx, row in gb.iterrows():
    if idx == 93:
        gb.set_value(idx, 'KNN_balance', row['KNN_ans'])
    else:
        gb.set_value(idx, 'KNN_balance', row['KNN_ans'] * gb.iloc[idx - 1]['KNN_balance'])
'''