In [1]:
import pandas as pd
import numpy as np
import json
import re

In [2]:
def open_files(date):
    focus_text = "2018-02-" + date + "_focus/2018-02-" + \
                 date + "_focus_group.json"
    krx_text = "krx_code.json"
    increase_text = "2018-02-" + date + "_opening_increase.json"
    price_text = "2018-02-" + date + "_price_and_everything.json"
    with open(focus_text, 'r', encoding='UTF-8') as focus_group:
        focus = json.load(focus_group)
    with open(krx_text, 'r', encoding='UTF-8') as krx:
        krx_code = json.load(krx)
    with open(increase_text, 'r', encoding='UTF-8') as oi:
        INCREASE = json.load(oi)
    with open(price_text, 'r', encoding='UTF-8') as oi:
        price = json.load(oi)
    
    return focus, krx_code, INCREASE, price

In [61]:
def get_time_disc(date):
    
    time = []
    prefix = "2018-02-" + date + "_focus/discussion_2018-02-" + date
    for hour in range(9,16):
        for minute in range(0, 6):
            time.append(prefix + " " + (("0" + str(hour)) if hour <= 9 else str(hour))+ \
                        ":" + str(minute) + "0.json")
    
    time = time[1:40]
    
    return time

In [62]:
def df_list_dis(date):
    df_list = []
    time = get_time_disc(date)
    for x in time:
        with open(x, 'r', encoding='UTF-8') as f:
            discussion = json.load(f)        
            discuss_df = pd.DataFrame(discussion, columns = ["post_num", \
                                "unique_id", "click", "like", "dislike", 
                                "name", "time"])
            reset_col = ["name", "time", "post_num", "unique_id", "click", \
                         "like", "dislike"]
            discuss_df = discuss_df[reset_col]
            df_list.append(discuss_df)
    return df_list

In [63]:
def list_to_df(date, df_list, column_names, key_list):
    total = pd.DataFrame(columns=column_names)
    for ind, df in enumerate(df_list):
        if ((ind + 1) % 3  == 0) and (ind != 2):
            df_total = df.merge(df_list[ind - 5], on = \
                                key_list).merge(df_list[ind - 4], \
                                on = key_list).merge(df_list[ind - 3], on = key_list)
            df_total.columns = column_names
            total = pd.concat([total, df_total], axis = 0)
            total = total[total["name"].isin(INCREASE)]   
    
    return total

In [64]:
COLUMN_DISC =["name", "time", "post_num", "unique_id", "click", \
              "like", "dislike", "time_1", "post_num_1", "unique_id_1", "click_1", \
              "like_1", "dislike_1", "time_2", "post_num_2", "unique_id_2", "click_2", \
              "like_2", "dislike_2", "time_3", "post_num_3", "unique_id_3", "click_3", \
              "like_3", "dislike_3"]

def get_discuss_df(date):
    discussion_list = df_list_dis(date)
    discuss_df = list_to_df(date, discussion_list, COLUMN_DISC, 
                            ['name']).reset_index().drop(["index"], axis = 1)
    return discuss_df

In [65]:
def df_list_price(date):
    price_df = pd.DataFrame(price, columns = ["index", "code", "name", "time", "price", \
                                         "price_dif", "sell", "buy", "volume", "variation"])
    price_df = price_df[["code", "name", "time", "price", \
                    "price_dif", "sell", "buy", "volume", "variation"]][1:]
    text = "2018-02-" + date + " 09:00"
    price_df = price_df[price_df["time"] != text]
    time_list = price_df['time'].unique().tolist()
    price_df_list = []
    for time in time_list:
        df = price_df[price_df["time"] == time]
        df = df[["code", "name", "time", "price", \
                "price_dif", "sell", "buy", "volume", "variation"]]
        price_df_list.append(df)
        
    return price_df_list

In [66]:
COLUMN_PRICE=["code", "name", "time", "price", "price_dif", "sell", 
              "buy", "volume", "variation", "time_1", "price_1", 
              "price_dif_1", "sell_1", "buy_1", "volume_1", "variation_1",
              "time_2", "price_2", "price_dif_2", "sell_2", "buy_2", 
              "volume_2", "variation_2", "time_3", "price_3", 
              "price_dif_3", "sell_3", "buy_3", "volume_3", "variation_3"]

def get_price_df(date):
    price_df_list = df_list_price(date)
    price_df = list_to_df(date, price_df_list, COLUMN_PRICE, \
                          ['code', 'name']).reset_index().drop(["index"], axis = 1)
    
    return price_df

In [67]:
COLUMN_TOTAL = ['name', 'code', 'time', 'price', 'time_1', "price_1", \
                "price_dif_1", "sell_1", "buy_1", "volume_1", "variation_1", \
                'post_num_1', 'unique_id_1', 'click_1', 'like_1', 'dislike_1', \
                'time_2', 'price_2', "price_dif_2", "sell_2", "buy_2", \
                "volume_2", "variation_2", 'post_num_2', 'unique_id_2', 'click_2', \
                'like_2', 'dislike_2', 'time_3', 'price_3', "price_dif_3", \
                "sell_3", "buy_3", "volume_3", "variation_3", 'post_num_3', \
                'unique_id_3', 'click_3', 'like_3', 'dislike_3']

def get_total_df(date):
    price_df = get_price_df(date)
    discuss_df = get_discuss_df(date)
    total_df = pd.merge(price_df, discuss_df, on = ['name', \
                                                    'time', 'time_1', 'time_2', 'time_3'])
    total_df = total_df[COLUMN_TOTAL]
    
    return total_df

In [68]:
import numpy as np
import re

with open("company_size.json", 'r', encoding='UTF-8') as f:
    company_size = json.load(f)

company_df = pd.DataFrame({"company_name": np.zeros(0), \
                           "code": np.zeros(0), "market": np.zeros(0), 
                          "company_size": np.zeros(0)})

company_df = pd.DataFrame(company_size, columns = ["name", "code", "market", "size"])

KOSPI = []
KOSDAQ = []
TRASH = []
MKT_CAP = {}

for idx, row in company_df.iterrows():
    if re.sub('[0-9 ,위]', '', row["market"]) == "코스피":
        KOSPI.append(row["code"])
    elif re.sub('[0-9 ,위]', '', row["market"]) == "코스닥":
        KOSDAQ.append(row["code"])
    else:
        TRASH.append(row["code"])
    
    MKT_CAP[row["code"]] = int(re.sub('[조억원,]', '', row["size"]))

In [69]:
def add_company(date):
    
    total = get_total_df(date)
    total["mkt_cap"] = np.nan
    total["kospi"] = np.nan
    total["kosdaq"] = np.nan
    total["trash"] = np.nan
    
    for index, row in total.iterrows():
        mkt_cap = MKT_CAP[row["code"]]
        if row["code"] in KOSPI:
            kospi = 1
        else:
            kospi = 0

        if row["code"] in KOSDAQ:
            kosdaq = 1
        else:
            kosdaq = 0

        if row["code"] in TRASH:
            trash = 1
        else:
            trash = 0
        total.set_value(index,'mkt_cap', mkt_cap)
        total.set_value(index,'kospi', kospi)
        total.set_value(index,'kosdaq', kosdaq)
        total.set_value(index,'trash', trash)  
    
    return total

In [70]:
def transform_df(date):
    
    total = add_company(date)   
    var_to_transform = ['price', 'price_1', 'price_dif_1', 'sell_1', 
                        'buy_1', 'volume_1', 'variation_1', 'price_2', 
                        'price_dif_2', 'sell_2', 'buy_2', 'volume_2', 
                        'variation_2', 'price_3', 'price_dif_3', 'sell_3', 'buy_3', 
                        'volume_3', 'variation_3']
    for index, row in total.iterrows():
        for var in var_to_transform:
            if isinstance(row[var], str):

                data = row[var].split(",")
                value = ''.join(data)
                value = int(value)
                total.set_value(index, var, value)
    return total

In [71]:
focus, krx_code, INCREASE, price = open_files('14')
total_14 = transform_df('14')
focus, krx_code, INCREASE, price = open_files('20')
total_20 = transform_df('20')
focus, krx_code, INCREASE, price = open_files('21')
total_21 = transform_df('21')
focus, krx_code, INCREASE, price = open_files('22')
total_22 = transform_df('22')

In [25]:
focus, krx_code, INCREASE, price = open_files('23')
total_23 = transform_df('23')

In [26]:
total_df = pd.concat([total_14, total_20, total_21, total_22, total_23])

In [27]:
total_df = total_df.reset_index().drop(["index"], axis = 1)

In [29]:
total_df["yesterday_closing_price"] = total_df["price_1"] - total_df["price_dif_1"]

In [30]:
total_df["is_maximum"] = (((total_df["price_1"] / total_df["yesterday_closing_price"]) - 1) * 100 > 29.5) | \
(((total_df["price_2"] / total_df["yesterday_closing_price"]) - 1) * 100 > 29.5) | \
(((total_df["price_3"] / total_df["yesterday_closing_price"]) - 1) * 100 > 29.5)
total_df["is_maximum"] = total_df["is_maximum"].astype(int)

In [31]:
total_df["is_minimum"] = (((total_df["price_1"] / total_df["yesterday_closing_price"]) - 1) * 100 < -29.5) | \
(((total_df["price_2"] / total_df["yesterday_closing_price"]) - 1) * 100 < -29.5) | \
(((total_df["price_3"] / total_df["yesterday_closing_price"]) - 1) * 100 < -29.5)
total_df["is_minimum"] = total_df["is_maximum"].astype(int)

In [32]:
total_df["price_volatility"] = (((total_df[["price_1", "price_2", "price_3"]].max(axis=1)) / (total_df[["price_1", "price_2", "price_3"]].min(axis=1))) - 1) * 100

In [33]:
total_df["price_trend"] = (((total_df["price_1"] - total_df["price_2"]) < 0).astype(int) + ((total_df["price_2"] - total_df["price_3"]) < 0).astype(int)) - (((total_df["price_1"] - total_df["price_2"]) > 0).astype(int) + ((total_df["price_2"] - total_df["price_3"]) > 0).astype(int))

In [34]:
total_df["average_price_volatility"] = total_df["price_trend"] * total_df["price_volatility"] / 2

In [35]:
total_df["sell_minus_buy_1"] = total_df["sell_1"] - total_df["buy_1"]

In [36]:
total_df["sell_minus_buy_2"] = total_df["sell_2"] - total_df["buy_2"]

In [37]:
total_df["sell_minus_buy_3"] = total_df["sell_3"] - total_df["buy_3"]

In [38]:
total_df["is_price_gap_stable"] = ((total_df["sell_minus_buy_1"] == total_df["sell_minus_buy_2"]) & (total_df["sell_minus_buy_2"] == total_df["sell_minus_buy_3"])).astype(int)

In [39]:
total_df["price_gap_volatility"] = (((total_df[["sell_minus_buy_1", "sell_minus_buy_2", "sell_minus_buy_3"]].max(axis=1)) / (total_df[["sell_minus_buy_1", "sell_minus_buy_2", "sell_minus_buy_3"]].min(axis=1)))) - 1

In [40]:
total_df["is_like_higher"] = (total_df["like_3"] > total_df["dislike_3"]).astype(int)

In [41]:
total_df["volume_trend"] = ((((total_df["volume_3"]) - (total_df["volume_2"] * 1+1e-3)) \
 / ((total_df["volume_2"]) - (total_df["volume_1"] * 1-1e-4))) - 1) * 100

In [42]:
total_df["post_num_trend"] = ((((total_df["post_num_3"]) - (total_df["post_num_2"] * 1+1e-3)) \
 / ((total_df["post_num_2"]) - (total_df["post_num_1"] * 1-1e-4))) - 1) * 100

In [43]:
total_df["unique_id_trend"] = ((((total_df["unique_id_3"]) - (total_df["unique_id_2"] * 1+1e-3)) \
 / ((total_df["unique_id_2"]) - (total_df["unique_id_1"] * 1-1e-4))) - 1) * 100

In [44]:
total_df["click_trend"] = ((((total_df["click_3"]) - (total_df["click_2"] * 1+1e-3)) \
 / ((total_df["click_2"]) - (total_df["click_1"] * 1-1e-4))) - 1) * 100

In [45]:
total_df["price_increase"] = ((total_df["price"] / total_df["price_3"]) - 1) * 100

In [46]:
total_df["did_price_increase"] = (total_df["price_increase"] > 0).astype(int)

In [55]:
total_df.to_json('first_data_24.json', orient='values')

In [56]:
with open('first_data_24.json', 'r', encoding='UTF-8') as f:
    first_data = json.load(f)
len(first_data)

3408

In [60]:
NEW_COL = ['name', 'code', 'time', 'price', 'time_1', 'price_1', 'price_dif_1',
       'sell_1', 'buy_1', 'volume_1', 'variation_1', 'post_num_1',
       'unique_id_1', 'click_1', 'like_1', 'dislike_1', 'time_2', 'price_2',
       'price_dif_2', 'sell_2', 'buy_2', 'volume_2', 'variation_2',
       'post_num_2', 'unique_id_2', 'click_2', 'like_2', 'dislike_2', 'time_3',
       'price_3', 'price_dif_3', 'sell_3', 'buy_3', 'volume_3', 'variation_3',
       'post_num_3', 'unique_id_3', 'click_3', 'like_3', 'dislike_3',
       'mkt_cap', 'kospi', 'kosdaq', 'trash', 'yesterday_closing_price',
       'is_maximum', 'is_minimum', 'price_volatility', 'price_trend',
       'average_price_volatility', 'sell_minus_buy_1', 'sell_minus_buy_2',
       'sell_minus_buy_3', 'is_price_gap_stable', 'price_gap_volatility',
       'is_like_higher', 'volume_trend', 'post_num_trend', 'unique_id_trend',
       'click_trend', 'price_increase', 'did_price_increase']
df = pd.DataFrame(first_data, columns = NEW_COL)
df

,name,code,time,price,time_1,price_1,price_dif_1,sell_1,buy_1,volume_1,...,sell_minus_buy_3,is_price_gap_stable,price_gap_volatility,is_like_higher,volume_trend,post_num_trend,unique_id_trend,click_trend,price_increase,did_price_increase
0,호텔신라,008770,2018-02-14 10:00,83400,2018-02-14 09:10,84700,1800,84800,84700,29336,...,100,1,0.000000,1,72.839497,-1.001000e+02,-1.001000e+02,-4.371912e+01,-0.595948,0
1,대한광통신,010170,2018-02-14 10:00,7050,2018-02-14 09:10,7060,90,7060,7050,101713,...,10,1,0.000000,0,28.112719,2.998900e+06,2.998900e+06,1.419989e+08,-0.423729,0
2,포스코 ICT,022100,2018-02-14 10:00,8320,2018-02-14 09:10,8310,0,8330,8310,44311,...,10,0,1.000000,0,-47.320886,9.989000e+05,9.989000e+05,9.648149e+00,0.726392,1
3,한화케미칼,009830,2018-02-14 10:00,32350,2018-02-14 09:10,32700,550,32700,32650,32647,...,100,0,1.000000,0,120.856895,1.998700e+02,1.998700e+02,4.274101e+01,-0.614439,0
4,지엘팜텍,204840,2018-02-14 10:00,4760,2018-02-14 09:10,4680,50,4700,4680,114565,...,10,0,1.500000,0,-9.395762,-1.001000e+02,-1.001000e+02,-2.150576e+01,1.492537,1
5,코웰패션,033290,2018-02-14 10:00,5350,2018-02-14 09:10,5270,90,5280,5270,22780,...,20,0,1.000000,1,-30.075500,-1.100000e+03,-1.100000e+03,2.499531e+01,0.563910,1
6,대한항공,003490,2018-02-14 10:00,35900,2018-02-14 09:10,35700,300,35750,35700,7560,...,50,1,0.000000,0,-63.511978,-1.099890e-01,-1.099890e-01,1.684144e+02,0.701262,1
7,대한뉴팜,054670,2018-02-14 10:00,13750,2018-02-14 09:10,13800,0,13800,13750,2556,...,100,0,1.000000,0,-17.674236,-1.100000e+03,-1.100000e+03,-9.680937e+00,0.364964,1
8,레드캡투어,038390,2018-02-14 10:00,15350,2018-02-14 09:10,15350,100,15350,15200,7,...,150,1,0.000000,0,-0.109989,-1.100000e+03,-1.100000e+03,-1.100000e+03,0.000000,0
9,이마트,139480,2018-02-14 10:00,290000,2018-02-14 09:10,283500,5000,284000,283500,8469,...,500,1,0.000000,1,6.982417,-1.001000e+02,-1.001000e+02,1.833119e+02,0.869565,1
10,녹십자,006280,2018-02-14 10:00,204500,2018-02-14 09:10,201000,1500,201000,200000,910,...,1000,0,1.000000,1,-26.502231,-1.100000e+03,-1.100000e+03,2.856337e+01,-0.243902,0
11,GS,078930,2018-02-14 10:00,63000,2018-02-14 09:10,62600,100,62700,62600,2353,...,100,1,0.000000,1,75.348783,-1.100000e+03,-1.100000e+03,-2.001080e+01,0.478469,1
12,CJ헬로,037560,2018-02-14 10:00,8980,2018-02-14 09:10,8650,230,8650,8640,22839,...,10,0,6.000000,0,-24.886333,9.989000e+05,9.989000e+05,-1.111414e+01,2.745995,1
13,모토닉,009680,2018-02-14 10:00,10150,2018-02-14 09:10,10300,50,10300,10200,1289,...,100,1,0.000000,0,79.999410,-1.100000e+03,-1.100000e+03,-1.100000e+03,0.000000,0
14,AJ렌터카,068400,2018-02-14 10:00,10500,2018-02-14 09:10,10400,0,10550,10400,22181,...,50,0,2.000000,1,-65.788182,-1.100000e+03,-1.100000e+03,-4.848803e+01,0.478469,1
15,한국전자홀딩스,006200,2018-02-14 10:00,799,2018-02-14 09:10,795,-3,795,793,203,...,3,0,0.500000,0,-80.404837,-1.100000e+03,-1.100000e+03,-1.100000e+03,0.629723,1
16,일진머티리얼즈,020150,2018-02-14 10:00,32300,2018-02-14 09:10,32300,350,32250,32200,11043,...,50,0,1.000000,0,-38.796103,-6.670111e+01,-1.000500e+02,-2.439268e+00,1.095462,1
17,코위버,056360,2018-02-14 10:00,7790,2018-02-14 09:10,7870,120,7890,7870,9193,...,10,0,2.000000,0,-37.970351,-1.100000e+03,-1.100000e+03,-1.100000e+03,-0.510856,0
18,앱클론,174900,2018-02-14 10:00,55100,2018-02-14 09:10,54300,0,54300,54200,6199,...,200,0,1.000000,0,117.360627,9.989000e+05,9.989000e+05,1.899890e+07,1.848429,1
19,디에이치피코리아,131030,2018-02-14 10:00,10550,2018-02-14 09:10,10400,350,10450,10400,44083,...,50,1,0.000000,1,-2.430533,-1.100000e+03,-1.100000e+03,4.475963e+00,1.442308,1
20,지스마트글로벌,114570,2018-02-14 10:00,13700,2018-02-14 09:10,13850,650,13900,13850,65403,...,50,1,0.000000,1,-75.470653,-6.002080e+01,-7.502562e+01,-9.768392e+00,-0.363636,0
21,씨케이에이치,900120,2018-02-14 10:00,841,2018-02-14 09:10,846,1,852,846,3602,...,1,0,5.000000,1,-28.465269,-1.099890e-01,-1.099890e-01,9.258818e+01,0.119048,1
22,삼우엠스,082660,2018-02-14 10:00,836,2018-02-14 09:10,828,12,828,816,11173,...,11,0,5.000000,1,14256.171148,-1.100000e+03,-1.100000e+03,5.997680e+01,0.000000,0
23,인트론바이오,048530,2018-02-14 10:00,38300,2018-02-14 09:10,37650,-100,37650,37600,6363,...,50,1,0.000000,0,-44.216199,-1.100000e+03,-1.100000e+03,-1.892038e+01,1.591512,1
24,휴온스,243070,2018-02-14 10:00,95100,2018-02-14 09:10,94000,1900,94100,94000,2291,...,100,0,2.000000,0,58.835699,-1.100000e+03,-1.100000e+03,-1.100000e+03,1.170213,1
25,알서포트,131370,2018-02-14 10:00,2720,2018-02-14 09:10,2730,35,2735,2730,27044,...,10,0,2.000000,0,-57.696888,-1.100000e+03,-1.100000e+03,-1.100000e+03,-0.183486,0
26,에스에너지,095910,2018-02-14 10:00,6670,2018-02-14 09:10,6710,50,6710,6660,589,...,30,0,4.000000,0,165.008806,-1.001000e+02,-1.001000e+02,-1.765343e+01,-0.298954,0
27,키움증권,039490,2018-02-14 10:00,106500,2018-02-14 09:10,106000,500,106000,105500,2585,...,500,1,0.000000,0,-25.956343,-1.100000e+03,-1.100000e+03,-1.100000e+03,1.913876,1
28,녹십자셀,031390,2018-02-14 10:00,50700,2018-02-14 09:10,49750,-250,49800,49750,9144,...,100,0,1.000000,1,-50.327707,9.988001e+01,9.988001e+01,2.111075e+02,1.603206,1
29,성광벤드,014620,2018-02-14 10:00,12050,2018-02-14 09:10,12200,150,12250,12200,6521,...,50,1,0.000000,0,-36.129287,-1.100000e+03,-1.100000e+03,-1.100000e+03,-0.823045,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3378,SIMPAC Metal,090730,2018-02-23 15:30,11650,2018-02-23 14:40,11850,-50,11850,11750,24674,...,100,0,1.000000,0,-66.777030,-1.100000e+03,-1.100000e+03,-1.100000e+03,-1.271186,0
3379,펩트론,087010,2018-02-23 15:30,70400,2018-02-23 14:40,70000,2700,70100,70000,112904,...,100,1,0.000000,0,164.468633,-1.100000e+03,-1.100000e+03,-1.100000e+03,0.571429,1
3380,인터로조,119610,2018-02-23 15:30,41900,2018-02-23 14:40,41700,300,41750,41700,22077,...,50,1,0.000000,1,-35.480577,-1.100000e+03,-1.100000e+03,-2.002160e+01,0.600240,1
3381,원익,032940,2018-02-23 15:30,5050,2018-02-23 14:40,4995,-75,5000,4990,159412,...,20,0,1.000000,0,893.306293,-1.100000e+03,-1.100000e+03,-2.353574e+01,1.000000,1
3382,세아베스틸,001430,2018-02-23 15:30,27550,2018-02-23 14:40,27400,0,27450,27400,13767,...,50,1,0.000000,0,16.091633,-1.100000e+03,-1.100000e+03,3.329556e+01,0.731261,1
3383,코오롱인더,120110,2018-02-23 15:30,74100,2018-02-23 14:40,73800,-300,73900,73800,89342,...,200,0,1.000000,1,-47.003133,9.988001e+01,-1.099890e-01,1.785634e+01,0.406504,1
3384,대화제약,067080,2018-02-23 15:30,29150,2018-02-23 14:40,29000,400,29100,29000,146285,...,50,0,1.000000,0,-49.880081,-1.001100e+06,-1.001100e+06,-1.060353e+02,0.000000,0
3385,경남제약,053950,2018-02-23 15:30,17400,2018-02-23 14:40,17600,-100,17650,17600,390432,...,100,0,1.000000,0,-74.646662,-1.100000e+03,-1.100000e+03,-3.571809e+01,-0.571429,0
3386,라온시큐어,042510,2018-02-23 15:30,3625,2018-02-23 14:40,3610,10,3615,3610,351863,...,5,1,0.000000,0,252.986364,-1.100000e+03,-1.100000e+03,-1.212451e+01,0.415512,1
3387,동방,004140,2018-02-23 15:30,1545,2018-02-23 14:40,1545,-15,1550,1545,163751,...,5,1,0.000000,0,-65.282457,-1.100000e+03,-1.100000e+03,3.997720e+01,-0.322581,0
3388,SG,255220,2018-02-23 15:30,5420,2018-02-23 14:40,5370,-30,5380,5370,45466,...,20,0,1.000000,1,262.459326,-1.100000e+03,-1.100000e+03,6.243086e+00,0.743494,1
3389,미스터블루,207760,2018-02-23 15:30,3525,2018-02-23 14:40,3525,5,3525,3515,31239,...,10,1,0.000000,0,-9.630679,-1.100000e+03,-1.100000e+03,-5.001050e+01,0.000000,0
3390,대봉엘에스,078140,2018-02-23 15:30,12450,2018-02-23 14:40,12300,-150,12300,12250,367515,...,50,1,0.000000,1,116.829112,-1.100000e+03,-1.100000e+03,-3.793195e+01,0.809717,1
3391,대웅제약,069620,2018-02-23 15:30,183500,2018-02-23 14:40,184000,0,184000,183500,63845,...,500,1,0.000000,1,215.611676,-1.100000e+03,-1.100000e+03,-3.289544e+01,-0.271739,0
3392,성도이엔지,037350,2018-02-23 15:30,9450,2018-02-23 14:40,9400,220,9400,9380,203644,...,20,1,0.000000,1,19.292487,9.989000e+05,9.989000e+05,-3.735068e+01,0.105932,1
3393,삼일,032280,2018-02-23 15:30,2230,2018-02-23 14:40,2240,45,2240,2235,699260,...,5,1,0.000000,0,-39.236993,-1.001000e+02,-1.001000e+02,-2.632144e+01,-0.668151,0
3394,웰크론한텍,076080,2018-02-23 15:30,3130,2018-02-23 14:40,3130,-5,3135,3125,48564,...,10,1,0.000000,0,-99.585477,-1.100000e+03,-1.100000e+03,-1.100000e+03,0.000000,0
3395,더존비즈온,012510,2018-02-23 15:30,53700,2018-02-23 14:40,53200,-800,53200,53100,52192,...,200,0,1.000000,0,-42.080529,-1.100000e+03,-1.100000e+03,-1.707581e+01,0.939850,1
3396,멕아이씨에스,058110,2018-02-23 15:30,4940,2018-02-23 14:40,4890,30,4920,4890,19615,...,5,0,5.000000,0,402859.604039,-1.100000e+03,-1.100000e+03,-5.005250e+01,-0.101112,0
3397,화성밸브,039610,2018-02-23 15:30,5420,2018-02-23 14:40,5420,-80,5430,5420,1751,...,10,1,0.000000,0,-100.003333,-1.100000e+03,-1.100000e+03,1.998900e+06,-0.184162,0
3398,애경유화,161000,2018-02-23 15:30,17850,2018-02-23 14:40,18050,600,18100,18050,122815,...,50,1,0.000000,1,12.050310,-1.100000e+03,-1.100000e+03,1.211784e+01,-0.833333,0
3399,안트로젠,065660,2018-02-23 15:30,68000,2018-02-23 14:40,67500,-400,67500,67100,36331,...,100,0,3.000000,0,102.701947,-1.001000e+02,-1.001000e+02,6.010577e+01,2.564103,1
3400,에이디칩스,054630,2018-02-23 15:30,2920,2018-02-23 14:40,2925,80,2925,2920,3054588,...,5,1,0.000000,1,-22.852841,-1.100000e+03,-1.100000e+03,-1.634058e+01,-0.511073,0
3401,대우건설,047040,2018-02-23 15:30,5430,2018-02-23 14:40,5420,160,5430,5420,2171214,...,10,1,0.000000,1,-22.735658,9.989000e+05,-1.100000e+03,-1.621646e+01,0.555556,1
3402,CJ,001040,2018-02-23 15:30,168000,2018-02-23 14:40,167000,2000,167500,167000,58260,...,500,1,0.000000,1,-2.776324,-1.001000e+02,-1.001000e+02,-1.176542e+01,0.000000,0
3403,엔에스,217820,2018-02-23 15:30,18600,2018-02-23 14:40,18500,-150,18550,18500,30443,...,50,1,0.000000,0,36.784078,-1.100000e+03,-1.100000e+03,6.659289e+00,0.540541,1
3404,네오오토,212560,2018-02-23 15:30,5570,2018-02-23 14:40,5530,-70,5570,5530,21823,...,30,0,0.333333,0,25.802820,-1.100000e+03,-1.100000e+03,-8.001020e+01,0.541516,1
3405,캐스텍코리아,071850,2018-02-23 15:30,4250,2018-02-23 14:40,4200,-80,4245,4200,77783,...,35,0,8.000000,0,310.838996,-1.100000e+03,-1.100000e+03,-3.001070e+01,0.710900,1
3406,에이치엘비생명과학,067630,2018-02-23 15:30,8200,2018-02-23 14:40,8410,90,8420,8410,570467,...,10,1,0.000000,1,76.046362,9.989000e+05,-1.100000e+03,8.282604e+00,-1.913876,0
3407,S&T모티브,064960,2018-02-23 15:30,44600,2018-02-23 14:40,44500,-350,44500,44450,26635,...,50,1,0.000000,0,10.875012,-1.100000e+03,-1.100000e+03,-1.100000e+03,0.224719,1